package com.kuangshan.riskcontrol.model;

public class DatadictionaryT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datadictionary_t.DDItemID
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    private Integer dditemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datadictionary_t.DDCategoryNum
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    private String ddcategorynum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datadictionary_t.DDItemNum
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    private String dditemnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datadictionary_t.DDItemValue
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    private String dditemvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datadictionary_t.IsDelete
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    private String isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datadictionary_t.DDItemID
     *
     * @return the value of datadictionary_t.DDItemID
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    public Integer getDditemid() {
        return dditemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datadictionary_t.DDItemID
     *
     * @param dditemid the value for datadictionary_t.DDItemID
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    public void setDditemid(Integer dditemid) {
        this.dditemid = dditemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datadictionary_t.DDCategoryNum
     *
     * @return the value of datadictionary_t.DDCategoryNum
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    public String getDdcategorynum() {
        return ddcategorynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datadictionary_t.DDCategoryNum
     *
     * @param ddcategorynum the value for datadictionary_t.DDCategoryNum
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    public void setDdcategorynum(String ddcategorynum) {
        this.ddcategorynum = ddcategorynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datadictionary_t.DDItemNum
     *
     * @return the value of datadictionary_t.DDItemNum
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    public String getDditemnum() {
        return dditemnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datadictionary_t.DDItemNum
     *
     * @param dditemnum the value for datadictionary_t.DDItemNum
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    public void setDditemnum(String dditemnum) {
        this.dditemnum = dditemnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datadictionary_t.DDItemValue
     *
     * @return the value of datadictionary_t.DDItemValue
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    public String getDditemvalue() {
        return dditemvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datadictionary_t.DDItemValue
     *
     * @param dditemvalue the value for datadictionary_t.DDItemValue
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    public void setDditemvalue(String dditemvalue) {
        this.dditemvalue = dditemvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datadictionary_t.IsDelete
     *
     * @return the value of datadictionary_t.IsDelete
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datadictionary_t.IsDelete
     *
     * @param isdelete the value for datadictionary_t.IsDelete
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete;
    }
}