package com.kuangshan.riskcontrol.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EducationInfoTExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    public EducationInfoTExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEducation_idIsNull() {
            addCriterion("education_id is null");
            return (Criteria) this;
        }

        public Criteria andEducation_idIsNotNull() {
            addCriterion("education_id is not null");
            return (Criteria) this;
        }

        public Criteria andEducation_idEqualTo(Integer value) {
            addCriterion("education_id =", value, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idNotEqualTo(Integer value) {
            addCriterion("education_id <>", value, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idGreaterThan(Integer value) {
            addCriterion("education_id >", value, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("education_id >=", value, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idLessThan(Integer value) {
            addCriterion("education_id <", value, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idLessThanOrEqualTo(Integer value) {
            addCriterion("education_id <=", value, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idIn(List<Integer> values) {
            addCriterion("education_id in", values, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idNotIn(List<Integer> values) {
            addCriterion("education_id not in", values, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idBetween(Integer value1, Integer value2) {
            addCriterion("education_id between", value1, value2, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idNotBetween(Integer value1, Integer value2) {
            addCriterion("education_id not between", value1, value2, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_numIsNull() {
            addCriterion("education_num is null");
            return (Criteria) this;
        }

        public Criteria andEducation_numIsNotNull() {
            addCriterion("education_num is not null");
            return (Criteria) this;
        }

        public Criteria andEducation_numEqualTo(String value) {
            addCriterion("education_num =", value, "education_num");
            return (Criteria) this;
        }

        public Criteria andEducation_numNotEqualTo(String value) {
            addCriterion("education_num <>", value, "education_num");
            return (Criteria) this;
        }

        public Criteria andEducation_numGreaterThan(String value) {
            addCriterion("education_num >", value, "education_num");
            return (Criteria) this;
        }

        public Criteria andEducation_numGreaterThanOrEqualTo(String value) {
            addCriterion("education_num >=", value, "education_num");
            return (Criteria) this;
        }

        public Criteria andEducation_numLessThan(String value) {
            addCriterion("education_num <", value, "education_num");
            return (Criteria) this;
        }

        public Criteria andEducation_numLessThanOrEqualTo(String value) {
            addCriterion("education_num <=", value, "education_num");
            return (Criteria) this;
        }

        public Criteria andEducation_numLike(String value) {
            addCriterion("education_num like", value, "education_num");
            return (Criteria) this;
        }

        public Criteria andEducation_numNotLike(String value) {
            addCriterion("education_num not like", value, "education_num");
            return (Criteria) this;
        }

        public Criteria andEducation_numIn(List<String> values) {
            addCriterion("education_num in", values, "education_num");
            return (Criteria) this;
        }

        public Criteria andEducation_numNotIn(List<String> values) {
            addCriterion("education_num not in", values, "education_num");
            return (Criteria) this;
        }

        public Criteria andEducation_numBetween(String value1, String value2) {
            addCriterion("education_num between", value1, value2, "education_num");
            return (Criteria) this;
        }

        public Criteria andEducation_numNotBetween(String value1, String value2) {
            addCriterion("education_num not between", value1, value2, "education_num");
            return (Criteria) this;
        }

        public Criteria andEducation_nameIsNull() {
            addCriterion("education_name is null");
            return (Criteria) this;
        }

        public Criteria andEducation_nameIsNotNull() {
            addCriterion("education_name is not null");
            return (Criteria) this;
        }

        public Criteria andEducation_nameEqualTo(String value) {
            addCriterion("education_name =", value, "education_name");
            return (Criteria) this;
        }

        public Criteria andEducation_nameNotEqualTo(String value) {
            addCriterion("education_name <>", value, "education_name");
            return (Criteria) this;
        }

        public Criteria andEducation_nameGreaterThan(String value) {
            addCriterion("education_name >", value, "education_name");
            return (Criteria) this;
        }

        public Criteria andEducation_nameGreaterThanOrEqualTo(String value) {
            addCriterion("education_name >=", value, "education_name");
            return (Criteria) this;
        }

        public Criteria andEducation_nameLessThan(String value) {
            addCriterion("education_name <", value, "education_name");
            return (Criteria) this;
        }

        public Criteria andEducation_nameLessThanOrEqualTo(String value) {
            addCriterion("education_name <=", value, "education_name");
            return (Criteria) this;
        }

        public Criteria andEducation_nameLike(String value) {
            addCriterion("education_name like", value, "education_name");
            return (Criteria) this;
        }

        public Criteria andEducation_nameNotLike(String value) {
            addCriterion("education_name not like", value, "education_name");
            return (Criteria) this;
        }

        public Criteria andEducation_nameIn(List<String> values) {
            addCriterion("education_name in", values, "education_name");
            return (Criteria) this;
        }

        public Criteria andEducation_nameNotIn(List<String> values) {
            addCriterion("education_name not in", values, "education_name");
            return (Criteria) this;
        }

        public Criteria andEducation_nameBetween(String value1, String value2) {
            addCriterion("education_name between", value1, value2, "education_name");
            return (Criteria) this;
        }

        public Criteria andEducation_nameNotBetween(String value1, String value2) {
            addCriterion("education_name not between", value1, value2, "education_name");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idIsNull() {
            addCriterion("edu_category_id is null");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idIsNotNull() {
            addCriterion("edu_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idEqualTo(Integer value) {
            addCriterion("edu_category_id =", value, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idNotEqualTo(Integer value) {
            addCriterion("edu_category_id <>", value, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idGreaterThan(Integer value) {
            addCriterion("edu_category_id >", value, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("edu_category_id >=", value, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idLessThan(Integer value) {
            addCriterion("edu_category_id <", value, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idLessThanOrEqualTo(Integer value) {
            addCriterion("edu_category_id <=", value, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idIn(List<Integer> values) {
            addCriterion("edu_category_id in", values, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idNotIn(List<Integer> values) {
            addCriterion("edu_category_id not in", values, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idBetween(Integer value1, Integer value2) {
            addCriterion("edu_category_id between", value1, value2, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idNotBetween(Integer value1, Integer value2) {
            addCriterion("edu_category_id not between", value1, value2, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameIsNull() {
            addCriterion("institution_name is null");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameIsNotNull() {
            addCriterion("institution_name is not null");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameEqualTo(String value) {
            addCriterion("institution_name =", value, "institution_name");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameNotEqualTo(String value) {
            addCriterion("institution_name <>", value, "institution_name");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameGreaterThan(String value) {
            addCriterion("institution_name >", value, "institution_name");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameGreaterThanOrEqualTo(String value) {
            addCriterion("institution_name >=", value, "institution_name");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameLessThan(String value) {
            addCriterion("institution_name <", value, "institution_name");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameLessThanOrEqualTo(String value) {
            addCriterion("institution_name <=", value, "institution_name");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameLike(String value) {
            addCriterion("institution_name like", value, "institution_name");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameNotLike(String value) {
            addCriterion("institution_name not like", value, "institution_name");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameIn(List<String> values) {
            addCriterion("institution_name in", values, "institution_name");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameNotIn(List<String> values) {
            addCriterion("institution_name not in", values, "institution_name");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameBetween(String value1, String value2) {
            addCriterion("institution_name between", value1, value2, "institution_name");
            return (Criteria) this;
        }

        public Criteria andInstitution_nameNotBetween(String value1, String value2) {
            addCriterion("institution_name not between", value1, value2, "institution_name");
            return (Criteria) this;
        }

        public Criteria andEducation_contentIsNull() {
            addCriterion("education_content is null");
            return (Criteria) this;
        }

        public Criteria andEducation_contentIsNotNull() {
            addCriterion("education_content is not null");
            return (Criteria) this;
        }

        public Criteria andEducation_contentEqualTo(String value) {
            addCriterion("education_content =", value, "education_content");
            return (Criteria) this;
        }

        public Criteria andEducation_contentNotEqualTo(String value) {
            addCriterion("education_content <>", value, "education_content");
            return (Criteria) this;
        }

        public Criteria andEducation_contentGreaterThan(String value) {
            addCriterion("education_content >", value, "education_content");
            return (Criteria) this;
        }

        public Criteria andEducation_contentGreaterThanOrEqualTo(String value) {
            addCriterion("education_content >=", value, "education_content");
            return (Criteria) this;
        }

        public Criteria andEducation_contentLessThan(String value) {
            addCriterion("education_content <", value, "education_content");
            return (Criteria) this;
        }

        public Criteria andEducation_contentLessThanOrEqualTo(String value) {
            addCriterion("education_content <=", value, "education_content");
            return (Criteria) this;
        }

        public Criteria andEducation_contentLike(String value) {
            addCriterion("education_content like", value, "education_content");
            return (Criteria) this;
        }

        public Criteria andEducation_contentNotLike(String value) {
            addCriterion("education_content not like", value, "education_content");
            return (Criteria) this;
        }

        public Criteria andEducation_contentIn(List<String> values) {
            addCriterion("education_content in", values, "education_content");
            return (Criteria) this;
        }

        public Criteria andEducation_contentNotIn(List<String> values) {
            addCriterion("education_content not in", values, "education_content");
            return (Criteria) this;
        }

        public Criteria andEducation_contentBetween(String value1, String value2) {
            addCriterion("education_content between", value1, value2, "education_content");
            return (Criteria) this;
        }

        public Criteria andEducation_contentNotBetween(String value1, String value2) {
            addCriterion("education_content not between", value1, value2, "education_content");
            return (Criteria) this;
        }

        public Criteria andEducation_numberIsNull() {
            addCriterion("education_number is null");
            return (Criteria) this;
        }

        public Criteria andEducation_numberIsNotNull() {
            addCriterion("education_number is not null");
            return (Criteria) this;
        }

        public Criteria andEducation_numberEqualTo(Integer value) {
            addCriterion("education_number =", value, "education_number");
            return (Criteria) this;
        }

        public Criteria andEducation_numberNotEqualTo(Integer value) {
            addCriterion("education_number <>", value, "education_number");
            return (Criteria) this;
        }

        public Criteria andEducation_numberGreaterThan(Integer value) {
            addCriterion("education_number >", value, "education_number");
            return (Criteria) this;
        }

        public Criteria andEducation_numberGreaterThanOrEqualTo(Integer value) {
            addCriterion("education_number >=", value, "education_number");
            return (Criteria) this;
        }

        public Criteria andEducation_numberLessThan(Integer value) {
            addCriterion("education_number <", value, "education_number");
            return (Criteria) this;
        }

        public Criteria andEducation_numberLessThanOrEqualTo(Integer value) {
            addCriterion("education_number <=", value, "education_number");
            return (Criteria) this;
        }

        public Criteria andEducation_numberIn(List<Integer> values) {
            addCriterion("education_number in", values, "education_number");
            return (Criteria) this;
        }

        public Criteria andEducation_numberNotIn(List<Integer> values) {
            addCriterion("education_number not in", values, "education_number");
            return (Criteria) this;
        }

        public Criteria andEducation_numberBetween(Integer value1, Integer value2) {
            addCriterion("education_number between", value1, value2, "education_number");
            return (Criteria) this;
        }

        public Criteria andEducation_numberNotBetween(Integer value1, Integer value2) {
            addCriterion("education_number not between", value1, value2, "education_number");
            return (Criteria) this;
        }

        public Criteria andEducation_typeIsNull() {
            addCriterion("education_type is null");
            return (Criteria) this;
        }

        public Criteria andEducation_typeIsNotNull() {
            addCriterion("education_type is not null");
            return (Criteria) this;
        }

        public Criteria andEducation_typeEqualTo(String value) {
            addCriterion("education_type =", value, "education_type");
            return (Criteria) this;
        }

        public Criteria andEducation_typeNotEqualTo(String value) {
            addCriterion("education_type <>", value, "education_type");
            return (Criteria) this;
        }

        public Criteria andEducation_typeGreaterThan(String value) {
            addCriterion("education_type >", value, "education_type");
            return (Criteria) this;
        }

        public Criteria andEducation_typeGreaterThanOrEqualTo(String value) {
            addCriterion("education_type >=", value, "education_type");
            return (Criteria) this;
        }

        public Criteria andEducation_typeLessThan(String value) {
            addCriterion("education_type <", value, "education_type");
            return (Criteria) this;
        }

        public Criteria andEducation_typeLessThanOrEqualTo(String value) {
            addCriterion("education_type <=", value, "education_type");
            return (Criteria) this;
        }

        public Criteria andEducation_typeLike(String value) {
            addCriterion("education_type like", value, "education_type");
            return (Criteria) this;
        }

        public Criteria andEducation_typeNotLike(String value) {
            addCriterion("education_type not like", value, "education_type");
            return (Criteria) this;
        }

        public Criteria andEducation_typeIn(List<String> values) {
            addCriterion("education_type in", values, "education_type");
            return (Criteria) this;
        }

        public Criteria andEducation_typeNotIn(List<String> values) {
            addCriterion("education_type not in", values, "education_type");
            return (Criteria) this;
        }

        public Criteria andEducation_typeBetween(String value1, String value2) {
            addCriterion("education_type between", value1, value2, "education_type");
            return (Criteria) this;
        }

        public Criteria andEducation_typeNotBetween(String value1, String value2) {
            addCriterion("education_type not between", value1, value2, "education_type");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorIsNull() {
            addCriterion("education_tutor is null");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorIsNotNull() {
            addCriterion("education_tutor is not null");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorEqualTo(String value) {
            addCriterion("education_tutor =", value, "education_tutor");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorNotEqualTo(String value) {
            addCriterion("education_tutor <>", value, "education_tutor");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorGreaterThan(String value) {
            addCriterion("education_tutor >", value, "education_tutor");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorGreaterThanOrEqualTo(String value) {
            addCriterion("education_tutor >=", value, "education_tutor");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorLessThan(String value) {
            addCriterion("education_tutor <", value, "education_tutor");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorLessThanOrEqualTo(String value) {
            addCriterion("education_tutor <=", value, "education_tutor");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorLike(String value) {
            addCriterion("education_tutor like", value, "education_tutor");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorNotLike(String value) {
            addCriterion("education_tutor not like", value, "education_tutor");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorIn(List<String> values) {
            addCriterion("education_tutor in", values, "education_tutor");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorNotIn(List<String> values) {
            addCriterion("education_tutor not in", values, "education_tutor");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorBetween(String value1, String value2) {
            addCriterion("education_tutor between", value1, value2, "education_tutor");
            return (Criteria) this;
        }

        public Criteria andEducation_tutorNotBetween(String value1, String value2) {
            addCriterion("education_tutor not between", value1, value2, "education_tutor");
            return (Criteria) this;
        }

        public Criteria andEducation_materialIsNull() {
            addCriterion("education_material is null");
            return (Criteria) this;
        }

        public Criteria andEducation_materialIsNotNull() {
            addCriterion("education_material is not null");
            return (Criteria) this;
        }

        public Criteria andEducation_materialEqualTo(String value) {
            addCriterion("education_material =", value, "education_material");
            return (Criteria) this;
        }

        public Criteria andEducation_materialNotEqualTo(String value) {
            addCriterion("education_material <>", value, "education_material");
            return (Criteria) this;
        }

        public Criteria andEducation_materialGreaterThan(String value) {
            addCriterion("education_material >", value, "education_material");
            return (Criteria) this;
        }

        public Criteria andEducation_materialGreaterThanOrEqualTo(String value) {
            addCriterion("education_material >=", value, "education_material");
            return (Criteria) this;
        }

        public Criteria andEducation_materialLessThan(String value) {
            addCriterion("education_material <", value, "education_material");
            return (Criteria) this;
        }

        public Criteria andEducation_materialLessThanOrEqualTo(String value) {
            addCriterion("education_material <=", value, "education_material");
            return (Criteria) this;
        }

        public Criteria andEducation_materialLike(String value) {
            addCriterion("education_material like", value, "education_material");
            return (Criteria) this;
        }

        public Criteria andEducation_materialNotLike(String value) {
            addCriterion("education_material not like", value, "education_material");
            return (Criteria) this;
        }

        public Criteria andEducation_materialIn(List<String> values) {
            addCriterion("education_material in", values, "education_material");
            return (Criteria) this;
        }

        public Criteria andEducation_materialNotIn(List<String> values) {
            addCriterion("education_material not in", values, "education_material");
            return (Criteria) this;
        }

        public Criteria andEducation_materialBetween(String value1, String value2) {
            addCriterion("education_material between", value1, value2, "education_material");
            return (Criteria) this;
        }

        public Criteria andEducation_materialNotBetween(String value1, String value2) {
            addCriterion("education_material not between", value1, value2, "education_material");
            return (Criteria) this;
        }

        public Criteria andEducation_budgetIsNull() {
            addCriterion("education_budget is null");
            return (Criteria) this;
        }

        public Criteria andEducation_budgetIsNotNull() {
            addCriterion("education_budget is not null");
            return (Criteria) this;
        }

        public Criteria andEducation_budgetEqualTo(BigDecimal value) {
            addCriterion("education_budget =", value, "education_budget");
            return (Criteria) this;
        }

        public Criteria andEducation_budgetNotEqualTo(BigDecimal value) {
            addCriterion("education_budget <>", value, "education_budget");
            return (Criteria) this;
        }

        public Criteria andEducation_budgetGreaterThan(BigDecimal value) {
            addCriterion("education_budget >", value, "education_budget");
            return (Criteria) this;
        }

        public Criteria andEducation_budgetGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("education_budget >=", value, "education_budget");
            return (Criteria) this;
        }

        public Criteria andEducation_budgetLessThan(BigDecimal value) {
            addCriterion("education_budget <", value, "education_budget");
            return (Criteria) this;
        }

        public Criteria andEducation_budgetLessThanOrEqualTo(BigDecimal value) {
            addCriterion("education_budget <=", value, "education_budget");
            return (Criteria) this;
        }

        public Criteria andEducation_budgetIn(List<BigDecimal> values) {
            addCriterion("education_budget in", values, "education_budget");
            return (Criteria) this;
        }

        public Criteria andEducation_budgetNotIn(List<BigDecimal> values) {
            addCriterion("education_budget not in", values, "education_budget");
            return (Criteria) this;
        }

        public Criteria andEducation_budgetBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("education_budget between", value1, value2, "education_budget");
            return (Criteria) this;
        }

        public Criteria andEducation_budgetNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("education_budget not between", value1, value2, "education_budget");
            return (Criteria) this;
        }

        public Criteria andStart_timeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStart_timeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStart_timeEqualTo(Date value) {
            addCriterion("start_time =", value, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeGreaterThan(Date value) {
            addCriterion("start_time >", value, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeLessThan(Date value) {
            addCriterion("start_time <", value, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeIn(List<Date> values) {
            addCriterion("start_time in", values, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "start_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEnd_timeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEnd_timeEqualTo(Date value) {
            addCriterion("end_time =", value, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeGreaterThan(Date value) {
            addCriterion("end_time >", value, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeLessThan(Date value) {
            addCriterion("end_time <", value, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeIn(List<Date> values) {
            addCriterion("end_time in", values, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "end_time");
            return (Criteria) this;
        }

        public Criteria andEducation_addressIsNull() {
            addCriterion("education_address is null");
            return (Criteria) this;
        }

        public Criteria andEducation_addressIsNotNull() {
            addCriterion("education_address is not null");
            return (Criteria) this;
        }

        public Criteria andEducation_addressEqualTo(String value) {
            addCriterion("education_address =", value, "education_address");
            return (Criteria) this;
        }

        public Criteria andEducation_addressNotEqualTo(String value) {
            addCriterion("education_address <>", value, "education_address");
            return (Criteria) this;
        }

        public Criteria andEducation_addressGreaterThan(String value) {
            addCriterion("education_address >", value, "education_address");
            return (Criteria) this;
        }

        public Criteria andEducation_addressGreaterThanOrEqualTo(String value) {
            addCriterion("education_address >=", value, "education_address");
            return (Criteria) this;
        }

        public Criteria andEducation_addressLessThan(String value) {
            addCriterion("education_address <", value, "education_address");
            return (Criteria) this;
        }

        public Criteria andEducation_addressLessThanOrEqualTo(String value) {
            addCriterion("education_address <=", value, "education_address");
            return (Criteria) this;
        }

        public Criteria andEducation_addressLike(String value) {
            addCriterion("education_address like", value, "education_address");
            return (Criteria) this;
        }

        public Criteria andEducation_addressNotLike(String value) {
            addCriterion("education_address not like", value, "education_address");
            return (Criteria) this;
        }

        public Criteria andEducation_addressIn(List<String> values) {
            addCriterion("education_address in", values, "education_address");
            return (Criteria) this;
        }

        public Criteria andEducation_addressNotIn(List<String> values) {
            addCriterion("education_address not in", values, "education_address");
            return (Criteria) this;
        }

        public Criteria andEducation_addressBetween(String value1, String value2) {
            addCriterion("education_address between", value1, value2, "education_address");
            return (Criteria) this;
        }

        public Criteria andEducation_addressNotBetween(String value1, String value2) {
            addCriterion("education_address not between", value1, value2, "education_address");
            return (Criteria) this;
        }

        public Criteria andEducation_periodIsNull() {
            addCriterion("education_period is null");
            return (Criteria) this;
        }

        public Criteria andEducation_periodIsNotNull() {
            addCriterion("education_period is not null");
            return (Criteria) this;
        }

        public Criteria andEducation_periodEqualTo(Integer value) {
            addCriterion("education_period =", value, "education_period");
            return (Criteria) this;
        }

        public Criteria andEducation_periodNotEqualTo(Integer value) {
            addCriterion("education_period <>", value, "education_period");
            return (Criteria) this;
        }

        public Criteria andEducation_periodGreaterThan(Integer value) {
            addCriterion("education_period >", value, "education_period");
            return (Criteria) this;
        }

        public Criteria andEducation_periodGreaterThanOrEqualTo(Integer value) {
            addCriterion("education_period >=", value, "education_period");
            return (Criteria) this;
        }

        public Criteria andEducation_periodLessThan(Integer value) {
            addCriterion("education_period <", value, "education_period");
            return (Criteria) this;
        }

        public Criteria andEducation_periodLessThanOrEqualTo(Integer value) {
            addCriterion("education_period <=", value, "education_period");
            return (Criteria) this;
        }

        public Criteria andEducation_periodIn(List<Integer> values) {
            addCriterion("education_period in", values, "education_period");
            return (Criteria) this;
        }

        public Criteria andEducation_periodNotIn(List<Integer> values) {
            addCriterion("education_period not in", values, "education_period");
            return (Criteria) this;
        }

        public Criteria andEducation_periodBetween(Integer value1, Integer value2) {
            addCriterion("education_period between", value1, value2, "education_period");
            return (Criteria) this;
        }

        public Criteria andEducation_periodNotBetween(Integer value1, Integer value2) {
            addCriterion("education_period not between", value1, value2, "education_period");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetIsNull() {
            addCriterion("online_edu_res_idset is null");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetIsNotNull() {
            addCriterion("online_edu_res_idset is not null");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetEqualTo(String value) {
            addCriterion("online_edu_res_idset =", value, "online_edu_res_idset");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetNotEqualTo(String value) {
            addCriterion("online_edu_res_idset <>", value, "online_edu_res_idset");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetGreaterThan(String value) {
            addCriterion("online_edu_res_idset >", value, "online_edu_res_idset");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetGreaterThanOrEqualTo(String value) {
            addCriterion("online_edu_res_idset >=", value, "online_edu_res_idset");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetLessThan(String value) {
            addCriterion("online_edu_res_idset <", value, "online_edu_res_idset");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetLessThanOrEqualTo(String value) {
            addCriterion("online_edu_res_idset <=", value, "online_edu_res_idset");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetLike(String value) {
            addCriterion("online_edu_res_idset like", value, "online_edu_res_idset");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetNotLike(String value) {
            addCriterion("online_edu_res_idset not like", value, "online_edu_res_idset");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetIn(List<String> values) {
            addCriterion("online_edu_res_idset in", values, "online_edu_res_idset");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetNotIn(List<String> values) {
            addCriterion("online_edu_res_idset not in", values, "online_edu_res_idset");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetBetween(String value1, String value2) {
            addCriterion("online_edu_res_idset between", value1, value2, "online_edu_res_idset");
            return (Criteria) this;
        }

        public Criteria andOnline_edu_res_idsetNotBetween(String value1, String value2) {
            addCriterion("online_edu_res_idset not between", value1, value2, "online_edu_res_idset");
            return (Criteria) this;
        }

        public Criteria andIs_finishedIsNull() {
            addCriterion("is_finished is null");
            return (Criteria) this;
        }

        public Criteria andIs_finishedIsNotNull() {
            addCriterion("is_finished is not null");
            return (Criteria) this;
        }

        public Criteria andIs_finishedEqualTo(Integer value) {
            addCriterion("is_finished =", value, "is_finished");
            return (Criteria) this;
        }

        public Criteria andIs_finishedNotEqualTo(Integer value) {
            addCriterion("is_finished <>", value, "is_finished");
            return (Criteria) this;
        }

        public Criteria andIs_finishedGreaterThan(Integer value) {
            addCriterion("is_finished >", value, "is_finished");
            return (Criteria) this;
        }

        public Criteria andIs_finishedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_finished >=", value, "is_finished");
            return (Criteria) this;
        }

        public Criteria andIs_finishedLessThan(Integer value) {
            addCriterion("is_finished <", value, "is_finished");
            return (Criteria) this;
        }

        public Criteria andIs_finishedLessThanOrEqualTo(Integer value) {
            addCriterion("is_finished <=", value, "is_finished");
            return (Criteria) this;
        }

        public Criteria andIs_finishedIn(List<Integer> values) {
            addCriterion("is_finished in", values, "is_finished");
            return (Criteria) this;
        }

        public Criteria andIs_finishedNotIn(List<Integer> values) {
            addCriterion("is_finished not in", values, "is_finished");
            return (Criteria) this;
        }

        public Criteria andIs_finishedBetween(Integer value1, Integer value2) {
            addCriterion("is_finished between", value1, value2, "is_finished");
            return (Criteria) this;
        }

        public Criteria andIs_finishedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_finished not between", value1, value2, "is_finished");
            return (Criteria) this;
        }

        public Criteria andIs_releasedIsNull() {
            addCriterion("is_released is null");
            return (Criteria) this;
        }

        public Criteria andIs_releasedIsNotNull() {
            addCriterion("is_released is not null");
            return (Criteria) this;
        }

        public Criteria andIs_releasedEqualTo(String value) {
            addCriterion("is_released =", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedNotEqualTo(String value) {
            addCriterion("is_released <>", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedGreaterThan(String value) {
            addCriterion("is_released >", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedGreaterThanOrEqualTo(String value) {
            addCriterion("is_released >=", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedLessThan(String value) {
            addCriterion("is_released <", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedLessThanOrEqualTo(String value) {
            addCriterion("is_released <=", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedLike(String value) {
            addCriterion("is_released like", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedNotLike(String value) {
            addCriterion("is_released not like", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedIn(List<String> values) {
            addCriterion("is_released in", values, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedNotIn(List<String> values) {
            addCriterion("is_released not in", values, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedBetween(String value1, String value2) {
            addCriterion("is_released between", value1, value2, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedNotBetween(String value1, String value2) {
            addCriterion("is_released not between", value1, value2, "is_released");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table education_info_t
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 29 12:40:12 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}