package com.kuangshan.riskcontrol.model;

import java.util.Date;

public class EducationResourceT {

    private String edu_category_name;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_resource_t.edu_resource_id
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    private Integer edu_resource_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_resource_t.resource_category
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    private Integer resource_category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_resource_t.resource_name
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    private String resource_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_resource_t.resource_introduction
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    private String resource_introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_resource_t.is_released
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    private Integer is_released;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_resource_t.resource_credit
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    private Integer resource_credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_resource_t.upload_person
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    private String upload_person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_resource_t.upload_time
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    private Date upload_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_resource_t.edu_resource_id
     *
     * @return the value of education_resource_t.edu_resource_id
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public Integer getEdu_resource_id() {
        return edu_resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_resource_t.edu_resource_id
     *
     * @param edu_resource_id the value for education_resource_t.edu_resource_id
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public void setEdu_resource_id(Integer edu_resource_id) {
        this.edu_resource_id = edu_resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_resource_t.resource_category
     *
     * @return the value of education_resource_t.resource_category
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public Integer getResource_category() {
        return resource_category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_resource_t.resource_category
     *
     * @param resource_category the value for education_resource_t.resource_category
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public void setResource_category(Integer resource_category) {
        this.resource_category = resource_category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_resource_t.resource_name
     *
     * @return the value of education_resource_t.resource_name
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public String getResource_name() {
        return resource_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_resource_t.resource_name
     *
     * @param resource_name the value for education_resource_t.resource_name
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public void setResource_name(String resource_name) {
        this.resource_name = resource_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_resource_t.resource_introduction
     *
     * @return the value of education_resource_t.resource_introduction
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public String getResource_introduction() {
        return resource_introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_resource_t.resource_introduction
     *
     * @param resource_introduction the value for education_resource_t.resource_introduction
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public void setResource_introduction(String resource_introduction) {
        this.resource_introduction = resource_introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_resource_t.is_released
     *
     * @return the value of education_resource_t.is_released
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public Integer getIs_released() {
        return is_released;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_resource_t.is_released
     *
     * @param is_released the value for education_resource_t.is_released
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public void setIs_released(Integer is_released) {
        this.is_released = is_released;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_resource_t.resource_credit
     *
     * @return the value of education_resource_t.resource_credit
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public Integer getResource_credit() {
        return resource_credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_resource_t.resource_credit
     *
     * @param resource_credit the value for education_resource_t.resource_credit
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public void setResource_credit(Integer resource_credit) {
        this.resource_credit = resource_credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_resource_t.upload_person
     *
     * @return the value of education_resource_t.upload_person
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public String getUpload_person() {
        return upload_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_resource_t.upload_person
     *
     * @param upload_person the value for education_resource_t.upload_person
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public void setUpload_person(String upload_person) {
        this.upload_person = upload_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_resource_t.upload_time
     *
     * @return the value of education_resource_t.upload_time
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public Date getUpload_time() {
        return upload_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_resource_t.upload_time
     *
     * @param upload_time the value for education_resource_t.upload_time
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    public void setUpload_time(Date upload_time) {
        this.upload_time = upload_time;
    }

    public String getEdu_category_name() {
        return edu_category_name;
    }

    public void setEdu_category_name(String edu_category_name) {
        this.edu_category_name = edu_category_name;
    }
}