package com.kuangshan.riskcontrol.model;

import java.util.Date;

/**
 *  培训资源类型 实体
 */
public class EducationCategoryT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_category_t.edu_category_id
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    private Integer edu_category_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_category_t.edu_category_name
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    private String edu_category_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_category_t.logo
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_category_t.deleted
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_category_t.creat_time
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    private Date creat_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_category_t.edu_category_id
     *
     * @return the value of education_category_t.edu_category_id
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    public Integer getEdu_category_id() {
        return edu_category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_category_t.edu_category_id
     *
     * @param edu_category_id the value for education_category_t.edu_category_id
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    public void setEdu_category_id(Integer edu_category_id) {
        this.edu_category_id = edu_category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_category_t.edu_category_name
     *
     * @return the value of education_category_t.edu_category_name
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    public String getEdu_category_name() {
        return edu_category_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_category_t.edu_category_name
     *
     * @param edu_category_name the value for education_category_t.edu_category_name
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    public void setEdu_category_name(String edu_category_name) {
        this.edu_category_name = edu_category_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_category_t.logo
     *
     * @return the value of education_category_t.logo
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_category_t.logo
     *
     * @param logo the value for education_category_t.logo
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_category_t.deleted
     *
     * @return the value of education_category_t.deleted
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_category_t.deleted
     *
     * @param deleted the value for education_category_t.deleted
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_category_t.creat_time
     *
     * @return the value of education_category_t.creat_time
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    public Date getCreat_time() {
        return creat_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_category_t.creat_time
     *
     * @param creat_time the value for education_category_t.creat_time
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    public void setCreat_time(Date creat_time) {
        this.creat_time = creat_time;
    }

    @Override
    public String toString() {
        return "EducationCategoryT{" +
                "edu_category_id=" + edu_category_id +
                ", edu_category_name='" + edu_category_name + '\'' +
                ", logo='" + logo + '\'' +
                ", deleted=" + deleted +
                ", creat_time=" + creat_time +
                '}';
    }
}