package com.kuangshan.riskcontrol.model;

import java.math.BigDecimal;
import java.util.Date;

public class EmployeeEducationReportT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education_report_t.employee_edu_report_id
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    private Integer employee_edu_report_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education_report_t.test_id
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    private Integer test_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education_report_t.test_name
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    private String test_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education_report_t.edu_category_id
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    private Integer edu_category_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education_report_t.employee_num
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    private String employee_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education_report_t.test_address
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    private String test_address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education_report_t.test_start_time
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    private Date test_start_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education_report_t.test_end_time
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    private Date test_end_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education_report_t.score
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education_report_t.makeup_grade
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    private BigDecimal makeup_grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education_report_t.score_mode
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    private String score_mode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education_report_t.employee_edu_report_id
     *
     * @return the value of employee_education_report_t.employee_edu_report_id
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public Integer getEmployee_edu_report_id() {
        return employee_edu_report_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education_report_t.employee_edu_report_id
     *
     * @param employee_edu_report_id the value for employee_education_report_t.employee_edu_report_id
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public void setEmployee_edu_report_id(Integer employee_edu_report_id) {
        this.employee_edu_report_id = employee_edu_report_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education_report_t.test_id
     *
     * @return the value of employee_education_report_t.test_id
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public Integer getTest_id() {
        return test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education_report_t.test_id
     *
     * @param test_id the value for employee_education_report_t.test_id
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public void setTest_id(Integer test_id) {
        this.test_id = test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education_report_t.test_name
     *
     * @return the value of employee_education_report_t.test_name
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public String getTest_name() {
        return test_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education_report_t.test_name
     *
     * @param test_name the value for employee_education_report_t.test_name
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public void setTest_name(String test_name) {
        this.test_name = test_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education_report_t.edu_category_id
     *
     * @return the value of employee_education_report_t.edu_category_id
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public Integer getEdu_category_id() {
        return edu_category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education_report_t.edu_category_id
     *
     * @param edu_category_id the value for employee_education_report_t.edu_category_id
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public void setEdu_category_id(Integer edu_category_id) {
        this.edu_category_id = edu_category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education_report_t.employee_num
     *
     * @return the value of employee_education_report_t.employee_num
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public String getEmployee_num() {
        return employee_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education_report_t.employee_num
     *
     * @param employee_num the value for employee_education_report_t.employee_num
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public void setEmployee_num(String employee_num) {
        this.employee_num = employee_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education_report_t.test_address
     *
     * @return the value of employee_education_report_t.test_address
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public String getTest_address() {
        return test_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education_report_t.test_address
     *
     * @param test_address the value for employee_education_report_t.test_address
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public void setTest_address(String test_address) {
        this.test_address = test_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education_report_t.test_start_time
     *
     * @return the value of employee_education_report_t.test_start_time
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public Date getTest_start_time() {
        return test_start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education_report_t.test_start_time
     *
     * @param test_start_time the value for employee_education_report_t.test_start_time
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public void setTest_start_time(Date test_start_time) {
        this.test_start_time = test_start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education_report_t.test_end_time
     *
     * @return the value of employee_education_report_t.test_end_time
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public Date getTest_end_time() {
        return test_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education_report_t.test_end_time
     *
     * @param test_end_time the value for employee_education_report_t.test_end_time
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public void setTest_end_time(Date test_end_time) {
        this.test_end_time = test_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education_report_t.score
     *
     * @return the value of employee_education_report_t.score
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education_report_t.score
     *
     * @param score the value for employee_education_report_t.score
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education_report_t.makeup_grade
     *
     * @return the value of employee_education_report_t.makeup_grade
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public BigDecimal getMakeup_grade() {
        return makeup_grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education_report_t.makeup_grade
     *
     * @param makeup_grade the value for employee_education_report_t.makeup_grade
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public void setMakeup_grade(BigDecimal makeup_grade) {
        this.makeup_grade = makeup_grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education_report_t.score_mode
     *
     * @return the value of employee_education_report_t.score_mode
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public String getScore_mode() {
        return score_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education_report_t.score_mode
     *
     * @param score_mode the value for employee_education_report_t.score_mode
     *
     * @mbg.generated Tue Mar 17 13:22:40 CST 2020
     */
    public void setScore_mode(String score_mode) {
        this.score_mode = score_mode;
    }
}