package com.kuangshan.riskcontrol.model;

public class EmployeeInstitutionDatadictionaryview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.EmployeeNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String employeeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.EmployeeID
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String employeeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.EmployeeName
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.EmployeeSex
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String employeeSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.EmployeeBirth
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String employeeBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.Photo
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.EmployeeIDNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String employeeIDNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.EmployeeTel
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String employeeTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.InstitutionNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String institutionNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.InstitutionName
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String institutionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.InstitutionPrefix
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String institutionPrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.CurrentWorkNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private Integer currentWorkNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.WorkStyleNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private Integer workStyleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.WorkPositionNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private Integer workPositionNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.InStationDate
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String inStationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.OutStationDate
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String outStationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.WorkType
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private Integer workType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.HomeAddress
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String homeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.JoinCompanyDate
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String joinCompanyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.OutCompanyDate
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String outCompanyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.OnState
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String onState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.RetireTime
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String retireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.IsRetire
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String isRetire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.CurrentWorkValue
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String currentWorkValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.WorkPositionValue
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String workPositionValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.WorkStyleValue
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String workStyleValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.workTypevalue
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String workTypevalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.OutCompanyOrNot
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String outCompanyOrNot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.Category
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.InsuranceNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String insuranceNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_institution_datadictionaryView.InsuredTime
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    private String insuredTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.EmployeeNum
     *
     * @return the value of employee_institution_datadictionaryView.EmployeeNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getEmployeeNum() {
        return employeeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.EmployeeNum
     *
     * @param employeeNum the value for employee_institution_datadictionaryView.EmployeeNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setEmployeeNum(String employeeNum) {
        this.employeeNum = employeeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.EmployeeID
     *
     * @return the value of employee_institution_datadictionaryView.EmployeeID
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getEmployeeID() {
        return employeeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.EmployeeID
     *
     * @param employeeID the value for employee_institution_datadictionaryView.EmployeeID
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setEmployeeID(String employeeID) {
        this.employeeID = employeeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.EmployeeName
     *
     * @return the value of employee_institution_datadictionaryView.EmployeeName
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.EmployeeName
     *
     * @param employeeName the value for employee_institution_datadictionaryView.EmployeeName
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.EmployeeSex
     *
     * @return the value of employee_institution_datadictionaryView.EmployeeSex
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getEmployeeSex() {
        return employeeSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.EmployeeSex
     *
     * @param employeeSex the value for employee_institution_datadictionaryView.EmployeeSex
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setEmployeeSex(String employeeSex) {
        this.employeeSex = employeeSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.EmployeeBirth
     *
     * @return the value of employee_institution_datadictionaryView.EmployeeBirth
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getEmployeeBirth() {
        return employeeBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.EmployeeBirth
     *
     * @param employeeBirth the value for employee_institution_datadictionaryView.EmployeeBirth
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setEmployeeBirth(String employeeBirth) {
        this.employeeBirth = employeeBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.Photo
     *
     * @return the value of employee_institution_datadictionaryView.Photo
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.Photo
     *
     * @param photo the value for employee_institution_datadictionaryView.Photo
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.EmployeeIDNum
     *
     * @return the value of employee_institution_datadictionaryView.EmployeeIDNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getEmployeeIDNum() {
        return employeeIDNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.EmployeeIDNum
     *
     * @param employeeIDNum the value for employee_institution_datadictionaryView.EmployeeIDNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setEmployeeIDNum(String employeeIDNum) {
        this.employeeIDNum = employeeIDNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.EmployeeTel
     *
     * @return the value of employee_institution_datadictionaryView.EmployeeTel
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getEmployeeTel() {
        return employeeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.EmployeeTel
     *
     * @param employeeTel the value for employee_institution_datadictionaryView.EmployeeTel
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setEmployeeTel(String employeeTel) {
        this.employeeTel = employeeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.InstitutionNum
     *
     * @return the value of employee_institution_datadictionaryView.InstitutionNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getInstitutionNum() {
        return institutionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.InstitutionNum
     *
     * @param institutionNum the value for employee_institution_datadictionaryView.InstitutionNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setInstitutionNum(String institutionNum) {
        this.institutionNum = institutionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.InstitutionName
     *
     * @return the value of employee_institution_datadictionaryView.InstitutionName
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getInstitutionName() {
        return institutionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.InstitutionName
     *
     * @param institutionName the value for employee_institution_datadictionaryView.InstitutionName
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.InstitutionPrefix
     *
     * @return the value of employee_institution_datadictionaryView.InstitutionPrefix
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getInstitutionPrefix() {
        return institutionPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.InstitutionPrefix
     *
     * @param institutionPrefix the value for employee_institution_datadictionaryView.InstitutionPrefix
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setInstitutionPrefix(String institutionPrefix) {
        this.institutionPrefix = institutionPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.CurrentWorkNum
     *
     * @return the value of employee_institution_datadictionaryView.CurrentWorkNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public Integer getCurrentWorkNum() {
        return currentWorkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.CurrentWorkNum
     *
     * @param currentWorkNum the value for employee_institution_datadictionaryView.CurrentWorkNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setCurrentWorkNum(Integer currentWorkNum) {
        this.currentWorkNum = currentWorkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.WorkStyleNum
     *
     * @return the value of employee_institution_datadictionaryView.WorkStyleNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public Integer getWorkStyleNum() {
        return workStyleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.WorkStyleNum
     *
     * @param workStyleNum the value for employee_institution_datadictionaryView.WorkStyleNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setWorkStyleNum(Integer workStyleNum) {
        this.workStyleNum = workStyleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.WorkPositionNum
     *
     * @return the value of employee_institution_datadictionaryView.WorkPositionNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public Integer getWorkPositionNum() {
        return workPositionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.WorkPositionNum
     *
     * @param workPositionNum the value for employee_institution_datadictionaryView.WorkPositionNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setWorkPositionNum(Integer workPositionNum) {
        this.workPositionNum = workPositionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.InStationDate
     *
     * @return the value of employee_institution_datadictionaryView.InStationDate
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getInStationDate() {
        return inStationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.InStationDate
     *
     * @param inStationDate the value for employee_institution_datadictionaryView.InStationDate
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setInStationDate(String inStationDate) {
        this.inStationDate = inStationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.OutStationDate
     *
     * @return the value of employee_institution_datadictionaryView.OutStationDate
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getOutStationDate() {
        return outStationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.OutStationDate
     *
     * @param outStationDate the value for employee_institution_datadictionaryView.OutStationDate
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setOutStationDate(String outStationDate) {
        this.outStationDate = outStationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.WorkType
     *
     * @return the value of employee_institution_datadictionaryView.WorkType
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public Integer getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.WorkType
     *
     * @param workType the value for employee_institution_datadictionaryView.WorkType
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setWorkType(Integer workType) {
        this.workType = workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.HomeAddress
     *
     * @return the value of employee_institution_datadictionaryView.HomeAddress
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.HomeAddress
     *
     * @param homeAddress the value for employee_institution_datadictionaryView.HomeAddress
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.JoinCompanyDate
     *
     * @return the value of employee_institution_datadictionaryView.JoinCompanyDate
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getJoinCompanyDate() {
        return joinCompanyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.JoinCompanyDate
     *
     * @param joinCompanyDate the value for employee_institution_datadictionaryView.JoinCompanyDate
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setJoinCompanyDate(String joinCompanyDate) {
        this.joinCompanyDate = joinCompanyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.OutCompanyDate
     *
     * @return the value of employee_institution_datadictionaryView.OutCompanyDate
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getOutCompanyDate() {
        return outCompanyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.OutCompanyDate
     *
     * @param outCompanyDate the value for employee_institution_datadictionaryView.OutCompanyDate
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setOutCompanyDate(String outCompanyDate) {
        this.outCompanyDate = outCompanyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.OnState
     *
     * @return the value of employee_institution_datadictionaryView.OnState
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getOnState() {
        return onState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.OnState
     *
     * @param onState the value for employee_institution_datadictionaryView.OnState
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setOnState(String onState) {
        this.onState = onState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.RetireTime
     *
     * @return the value of employee_institution_datadictionaryView.RetireTime
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getRetireTime() {
        return retireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.RetireTime
     *
     * @param retireTime the value for employee_institution_datadictionaryView.RetireTime
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setRetireTime(String retireTime) {
        this.retireTime = retireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.IsRetire
     *
     * @return the value of employee_institution_datadictionaryView.IsRetire
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getIsRetire() {
        return isRetire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.IsRetire
     *
     * @param isRetire the value for employee_institution_datadictionaryView.IsRetire
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setIsRetire(String isRetire) {
        this.isRetire = isRetire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.CurrentWorkValue
     *
     * @return the value of employee_institution_datadictionaryView.CurrentWorkValue
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getCurrentWorkValue() {
        return currentWorkValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.CurrentWorkValue
     *
     * @param currentWorkValue the value for employee_institution_datadictionaryView.CurrentWorkValue
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setCurrentWorkValue(String currentWorkValue) {
        this.currentWorkValue = currentWorkValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.WorkPositionValue
     *
     * @return the value of employee_institution_datadictionaryView.WorkPositionValue
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getWorkPositionValue() {
        return workPositionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.WorkPositionValue
     *
     * @param workPositionValue the value for employee_institution_datadictionaryView.WorkPositionValue
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setWorkPositionValue(String workPositionValue) {
        this.workPositionValue = workPositionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.WorkStyleValue
     *
     * @return the value of employee_institution_datadictionaryView.WorkStyleValue
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getWorkStyleValue() {
        return workStyleValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.WorkStyleValue
     *
     * @param workStyleValue the value for employee_institution_datadictionaryView.WorkStyleValue
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setWorkStyleValue(String workStyleValue) {
        this.workStyleValue = workStyleValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.workTypevalue
     *
     * @return the value of employee_institution_datadictionaryView.workTypevalue
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getWorkTypevalue() {
        return workTypevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.workTypevalue
     *
     * @param workTypevalue the value for employee_institution_datadictionaryView.workTypevalue
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setWorkTypevalue(String workTypevalue) {
        this.workTypevalue = workTypevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.OutCompanyOrNot
     *
     * @return the value of employee_institution_datadictionaryView.OutCompanyOrNot
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getOutCompanyOrNot() {
        return outCompanyOrNot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.OutCompanyOrNot
     *
     * @param outCompanyOrNot the value for employee_institution_datadictionaryView.OutCompanyOrNot
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setOutCompanyOrNot(String outCompanyOrNot) {
        this.outCompanyOrNot = outCompanyOrNot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.Category
     *
     * @return the value of employee_institution_datadictionaryView.Category
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.Category
     *
     * @param category the value for employee_institution_datadictionaryView.Category
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.InsuranceNum
     *
     * @return the value of employee_institution_datadictionaryView.InsuranceNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getInsuranceNum() {
        return insuranceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.InsuranceNum
     *
     * @param insuranceNum the value for employee_institution_datadictionaryView.InsuranceNum
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setInsuranceNum(String insuranceNum) {
        this.insuranceNum = insuranceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_institution_datadictionaryView.InsuredTime
     *
     * @return the value of employee_institution_datadictionaryView.InsuredTime
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public String getInsuredTime() {
        return insuredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_institution_datadictionaryView.InsuredTime
     *
     * @param insuredTime the value for employee_institution_datadictionaryView.InsuredTime
     *
     * @mbg.generated Wed Jul 24 21:14:20 CST 2019
     */
    public void setInsuredTime(String insuredTime) {
        this.insuredTime = insuredTime;
    }
}