package com.kuangshan.riskcontrol.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InstitutionTExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    public InstitutionTExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInstitutionnumIsNull() {
            addCriterion("InstitutionNum is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumIsNotNull() {
            addCriterion("InstitutionNum is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumEqualTo(String value) {
            addCriterion("InstitutionNum =", value, "institutionnum");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumNotEqualTo(String value) {
            addCriterion("InstitutionNum <>", value, "institutionnum");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumGreaterThan(String value) {
            addCriterion("InstitutionNum >", value, "institutionnum");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumGreaterThanOrEqualTo(String value) {
            addCriterion("InstitutionNum >=", value, "institutionnum");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumLessThan(String value) {
            addCriterion("InstitutionNum <", value, "institutionnum");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumLessThanOrEqualTo(String value) {
            addCriterion("InstitutionNum <=", value, "institutionnum");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumLike(String value) {
            addCriterion("InstitutionNum like", value, "institutionnum");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumNotLike(String value) {
            addCriterion("InstitutionNum not like", value, "institutionnum");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumIn(List<String> values) {
            addCriterion("InstitutionNum in", values, "institutionnum");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumNotIn(List<String> values) {
            addCriterion("InstitutionNum not in", values, "institutionnum");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumBetween(String value1, String value2) {
            addCriterion("InstitutionNum between", value1, value2, "institutionnum");
            return (Criteria) this;
        }

        public Criteria andInstitutionnumNotBetween(String value1, String value2) {
            addCriterion("InstitutionNum not between", value1, value2, "institutionnum");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameIsNull() {
            addCriterion("InstitutionName is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameIsNotNull() {
            addCriterion("InstitutionName is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameEqualTo(String value) {
            addCriterion("InstitutionName =", value, "institutionname");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameNotEqualTo(String value) {
            addCriterion("InstitutionName <>", value, "institutionname");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameGreaterThan(String value) {
            addCriterion("InstitutionName >", value, "institutionname");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameGreaterThanOrEqualTo(String value) {
            addCriterion("InstitutionName >=", value, "institutionname");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameLessThan(String value) {
            addCriterion("InstitutionName <", value, "institutionname");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameLessThanOrEqualTo(String value) {
            addCriterion("InstitutionName <=", value, "institutionname");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameLike(String value) {
            addCriterion("InstitutionName like", value, "institutionname");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameNotLike(String value) {
            addCriterion("InstitutionName not like", value, "institutionname");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameIn(List<String> values) {
            addCriterion("InstitutionName in", values, "institutionname");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameNotIn(List<String> values) {
            addCriterion("InstitutionName not in", values, "institutionname");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameBetween(String value1, String value2) {
            addCriterion("InstitutionName between", value1, value2, "institutionname");
            return (Criteria) this;
        }

        public Criteria andInstitutionnameNotBetween(String value1, String value2) {
            addCriterion("InstitutionName not between", value1, value2, "institutionname");
            return (Criteria) this;
        }

        public Criteria andInstitutioncategorynumIsNull() {
            addCriterion("InstitutionCategoryNum is null");
            return (Criteria) this;
        }

        public Criteria andInstitutioncategorynumIsNotNull() {
            addCriterion("InstitutionCategoryNum is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutioncategorynumEqualTo(Integer value) {
            addCriterion("InstitutionCategoryNum =", value, "institutioncategorynum");
            return (Criteria) this;
        }

        public Criteria andInstitutioncategorynumNotEqualTo(Integer value) {
            addCriterion("InstitutionCategoryNum <>", value, "institutioncategorynum");
            return (Criteria) this;
        }

        public Criteria andInstitutioncategorynumGreaterThan(Integer value) {
            addCriterion("InstitutionCategoryNum >", value, "institutioncategorynum");
            return (Criteria) this;
        }

        public Criteria andInstitutioncategorynumGreaterThanOrEqualTo(Integer value) {
            addCriterion("InstitutionCategoryNum >=", value, "institutioncategorynum");
            return (Criteria) this;
        }

        public Criteria andInstitutioncategorynumLessThan(Integer value) {
            addCriterion("InstitutionCategoryNum <", value, "institutioncategorynum");
            return (Criteria) this;
        }

        public Criteria andInstitutioncategorynumLessThanOrEqualTo(Integer value) {
            addCriterion("InstitutionCategoryNum <=", value, "institutioncategorynum");
            return (Criteria) this;
        }

        public Criteria andInstitutioncategorynumIn(List<Integer> values) {
            addCriterion("InstitutionCategoryNum in", values, "institutioncategorynum");
            return (Criteria) this;
        }

        public Criteria andInstitutioncategorynumNotIn(List<Integer> values) {
            addCriterion("InstitutionCategoryNum not in", values, "institutioncategorynum");
            return (Criteria) this;
        }

        public Criteria andInstitutioncategorynumBetween(Integer value1, Integer value2) {
            addCriterion("InstitutionCategoryNum between", value1, value2, "institutioncategorynum");
            return (Criteria) this;
        }

        public Criteria andInstitutioncategorynumNotBetween(Integer value1, Integer value2) {
            addCriterion("InstitutionCategoryNum not between", value1, value2, "institutioncategorynum");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeIsNull() {
            addCriterion("PeopleInCharge is null");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeIsNotNull() {
            addCriterion("PeopleInCharge is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeEqualTo(String value) {
            addCriterion("PeopleInCharge =", value, "peopleincharge");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeNotEqualTo(String value) {
            addCriterion("PeopleInCharge <>", value, "peopleincharge");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeGreaterThan(String value) {
            addCriterion("PeopleInCharge >", value, "peopleincharge");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeGreaterThanOrEqualTo(String value) {
            addCriterion("PeopleInCharge >=", value, "peopleincharge");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeLessThan(String value) {
            addCriterion("PeopleInCharge <", value, "peopleincharge");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeLessThanOrEqualTo(String value) {
            addCriterion("PeopleInCharge <=", value, "peopleincharge");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeLike(String value) {
            addCriterion("PeopleInCharge like", value, "peopleincharge");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeNotLike(String value) {
            addCriterion("PeopleInCharge not like", value, "peopleincharge");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeIn(List<String> values) {
            addCriterion("PeopleInCharge in", values, "peopleincharge");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeNotIn(List<String> values) {
            addCriterion("PeopleInCharge not in", values, "peopleincharge");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeBetween(String value1, String value2) {
            addCriterion("PeopleInCharge between", value1, value2, "peopleincharge");
            return (Criteria) this;
        }

        public Criteria andPeopleinchargeNotBetween(String value1, String value2) {
            addCriterion("PeopleInCharge not between", value1, value2, "peopleincharge");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("Category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("Category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("Category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("Category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("Category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("Category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("Category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("Category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("Category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("Category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("Category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("Category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("Category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("Category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixIsNull() {
            addCriterion("InstitutionPrefix is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixIsNotNull() {
            addCriterion("InstitutionPrefix is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixEqualTo(String value) {
            addCriterion("InstitutionPrefix =", value, "institutionprefix");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixNotEqualTo(String value) {
            addCriterion("InstitutionPrefix <>", value, "institutionprefix");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixGreaterThan(String value) {
            addCriterion("InstitutionPrefix >", value, "institutionprefix");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixGreaterThanOrEqualTo(String value) {
            addCriterion("InstitutionPrefix >=", value, "institutionprefix");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixLessThan(String value) {
            addCriterion("InstitutionPrefix <", value, "institutionprefix");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixLessThanOrEqualTo(String value) {
            addCriterion("InstitutionPrefix <=", value, "institutionprefix");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixLike(String value) {
            addCriterion("InstitutionPrefix like", value, "institutionprefix");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixNotLike(String value) {
            addCriterion("InstitutionPrefix not like", value, "institutionprefix");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixIn(List<String> values) {
            addCriterion("InstitutionPrefix in", values, "institutionprefix");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixNotIn(List<String> values) {
            addCriterion("InstitutionPrefix not in", values, "institutionprefix");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixBetween(String value1, String value2) {
            addCriterion("InstitutionPrefix between", value1, value2, "institutionprefix");
            return (Criteria) this;
        }

        public Criteria andInstitutionprefixNotBetween(String value1, String value2) {
            addCriterion("InstitutionPrefix not between", value1, value2, "institutionprefix");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("IsDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("IsDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(String value) {
            addCriterion("IsDelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(String value) {
            addCriterion("IsDelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(String value) {
            addCriterion("IsDelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(String value) {
            addCriterion("IsDelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(String value) {
            addCriterion("IsDelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(String value) {
            addCriterion("IsDelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLike(String value) {
            addCriterion("IsDelete like", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotLike(String value) {
            addCriterion("IsDelete not like", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<String> values) {
            addCriterion("IsDelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<String> values) {
            addCriterion("IsDelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(String value1, String value2) {
            addCriterion("IsDelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(String value1, String value2) {
            addCriterion("IsDelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andEstablishtimeIsNull() {
            addCriterion("EstablishTime is null");
            return (Criteria) this;
        }

        public Criteria andEstablishtimeIsNotNull() {
            addCriterion("EstablishTime is not null");
            return (Criteria) this;
        }

        public Criteria andEstablishtimeEqualTo(Date value) {
            addCriterion("EstablishTime =", value, "establishtime");
            return (Criteria) this;
        }

        public Criteria andEstablishtimeNotEqualTo(Date value) {
            addCriterion("EstablishTime <>", value, "establishtime");
            return (Criteria) this;
        }

        public Criteria andEstablishtimeGreaterThan(Date value) {
            addCriterion("EstablishTime >", value, "establishtime");
            return (Criteria) this;
        }

        public Criteria andEstablishtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("EstablishTime >=", value, "establishtime");
            return (Criteria) this;
        }

        public Criteria andEstablishtimeLessThan(Date value) {
            addCriterion("EstablishTime <", value, "establishtime");
            return (Criteria) this;
        }

        public Criteria andEstablishtimeLessThanOrEqualTo(Date value) {
            addCriterion("EstablishTime <=", value, "establishtime");
            return (Criteria) this;
        }

        public Criteria andEstablishtimeIn(List<Date> values) {
            addCriterion("EstablishTime in", values, "establishtime");
            return (Criteria) this;
        }

        public Criteria andEstablishtimeNotIn(List<Date> values) {
            addCriterion("EstablishTime not in", values, "establishtime");
            return (Criteria) this;
        }

        public Criteria andEstablishtimeBetween(Date value1, Date value2) {
            addCriterion("EstablishTime between", value1, value2, "establishtime");
            return (Criteria) this;
        }

        public Criteria andEstablishtimeNotBetween(Date value1, Date value2) {
            addCriterion("EstablishTime not between", value1, value2, "establishtime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeIsNull() {
            addCriterion("DeleteTime is null");
            return (Criteria) this;
        }

        public Criteria andDeletetimeIsNotNull() {
            addCriterion("DeleteTime is not null");
            return (Criteria) this;
        }

        public Criteria andDeletetimeEqualTo(Date value) {
            addCriterion("DeleteTime =", value, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeNotEqualTo(Date value) {
            addCriterion("DeleteTime <>", value, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeGreaterThan(Date value) {
            addCriterion("DeleteTime >", value, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DeleteTime >=", value, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeLessThan(Date value) {
            addCriterion("DeleteTime <", value, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeLessThanOrEqualTo(Date value) {
            addCriterion("DeleteTime <=", value, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeIn(List<Date> values) {
            addCriterion("DeleteTime in", values, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeNotIn(List<Date> values) {
            addCriterion("DeleteTime not in", values, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeBetween(Date value1, Date value2) {
            addCriterion("DeleteTime between", value1, value2, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeNotBetween(Date value1, Date value2) {
            addCriterion("DeleteTime not between", value1, value2, "deletetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table institution_t
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 24 21:25:21 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}