package com.kuangshan.riskcontrol.model;

import java.math.BigDecimal;

public class OfflineTestPaperT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.paper_id
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private Integer paper_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.test_id
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private Integer test_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.total_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private Integer total_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.single_choose_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private BigDecimal single_choose_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.multi_choice_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private BigDecimal multi_choice_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.judge_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private BigDecimal judge_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.question_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private BigDecimal question_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.blanks_test_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private BigDecimal blanks_test_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.single_choose_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private Integer single_choose_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.multi_choice_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private Integer multi_choice_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.judge_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private Integer judge_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.question_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private Integer question_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.blanks_test_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private Integer blanks_test_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.single_choose
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private String single_choose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.multi_choice
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private String multi_choice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.judge
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private String judge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.question
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_test_paper_t.blanks_test
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    private String blanks_test;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.paper_id
     *
     * @return the value of offline_test_paper_t.paper_id
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public Integer getPaper_id() {
        return paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.paper_id
     *
     * @param paper_id the value for offline_test_paper_t.paper_id
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setPaper_id(Integer paper_id) {
        this.paper_id = paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.test_id
     *
     * @return the value of offline_test_paper_t.test_id
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public Integer getTest_id() {
        return test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.test_id
     *
     * @param test_id the value for offline_test_paper_t.test_id
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setTest_id(Integer test_id) {
        this.test_id = test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.total_score
     *
     * @return the value of offline_test_paper_t.total_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public Integer getTotal_score() {
        return total_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.total_score
     *
     * @param total_score the value for offline_test_paper_t.total_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setTotal_score(Integer total_score) {
        this.total_score = total_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.single_choose_score
     *
     * @return the value of offline_test_paper_t.single_choose_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public BigDecimal getSingle_choose_score() {
        return single_choose_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.single_choose_score
     *
     * @param single_choose_score the value for offline_test_paper_t.single_choose_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setSingle_choose_score(BigDecimal single_choose_score) {
        this.single_choose_score = single_choose_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.multi_choice_score
     *
     * @return the value of offline_test_paper_t.multi_choice_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public BigDecimal getMulti_choice_score() {
        return multi_choice_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.multi_choice_score
     *
     * @param multi_choice_score the value for offline_test_paper_t.multi_choice_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setMulti_choice_score(BigDecimal multi_choice_score) {
        this.multi_choice_score = multi_choice_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.judge_score
     *
     * @return the value of offline_test_paper_t.judge_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public BigDecimal getJudge_score() {
        return judge_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.judge_score
     *
     * @param judge_score the value for offline_test_paper_t.judge_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setJudge_score(BigDecimal judge_score) {
        this.judge_score = judge_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.question_score
     *
     * @return the value of offline_test_paper_t.question_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public BigDecimal getQuestion_score() {
        return question_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.question_score
     *
     * @param question_score the value for offline_test_paper_t.question_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setQuestion_score(BigDecimal question_score) {
        this.question_score = question_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.blanks_test_score
     *
     * @return the value of offline_test_paper_t.blanks_test_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public BigDecimal getBlanks_test_score() {
        return blanks_test_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.blanks_test_score
     *
     * @param blanks_test_score the value for offline_test_paper_t.blanks_test_score
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setBlanks_test_score(BigDecimal blanks_test_score) {
        this.blanks_test_score = blanks_test_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.single_choose_num
     *
     * @return the value of offline_test_paper_t.single_choose_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public Integer getSingle_choose_num() {
        return single_choose_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.single_choose_num
     *
     * @param single_choose_num the value for offline_test_paper_t.single_choose_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setSingle_choose_num(Integer single_choose_num) {
        this.single_choose_num = single_choose_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.multi_choice_num
     *
     * @return the value of offline_test_paper_t.multi_choice_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public Integer getMulti_choice_num() {
        return multi_choice_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.multi_choice_num
     *
     * @param multi_choice_num the value for offline_test_paper_t.multi_choice_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setMulti_choice_num(Integer multi_choice_num) {
        this.multi_choice_num = multi_choice_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.judge_num
     *
     * @return the value of offline_test_paper_t.judge_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public Integer getJudge_num() {
        return judge_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.judge_num
     *
     * @param judge_num the value for offline_test_paper_t.judge_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setJudge_num(Integer judge_num) {
        this.judge_num = judge_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.question_num
     *
     * @return the value of offline_test_paper_t.question_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public Integer getQuestion_num() {
        return question_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.question_num
     *
     * @param question_num the value for offline_test_paper_t.question_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setQuestion_num(Integer question_num) {
        this.question_num = question_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.blanks_test_num
     *
     * @return the value of offline_test_paper_t.blanks_test_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public Integer getBlanks_test_num() {
        return blanks_test_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.blanks_test_num
     *
     * @param blanks_test_num the value for offline_test_paper_t.blanks_test_num
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setBlanks_test_num(Integer blanks_test_num) {
        this.blanks_test_num = blanks_test_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.single_choose
     *
     * @return the value of offline_test_paper_t.single_choose
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public String getSingle_choose() {
        return single_choose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.single_choose
     *
     * @param single_choose the value for offline_test_paper_t.single_choose
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setSingle_choose(String single_choose) {
        this.single_choose = single_choose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.multi_choice
     *
     * @return the value of offline_test_paper_t.multi_choice
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public String getMulti_choice() {
        return multi_choice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.multi_choice
     *
     * @param multi_choice the value for offline_test_paper_t.multi_choice
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setMulti_choice(String multi_choice) {
        this.multi_choice = multi_choice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.judge
     *
     * @return the value of offline_test_paper_t.judge
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public String getJudge() {
        return judge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.judge
     *
     * @param judge the value for offline_test_paper_t.judge
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setJudge(String judge) {
        this.judge = judge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.question
     *
     * @return the value of offline_test_paper_t.question
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.question
     *
     * @param question the value for offline_test_paper_t.question
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_test_paper_t.blanks_test
     *
     * @return the value of offline_test_paper_t.blanks_test
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public String getBlanks_test() {
        return blanks_test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_test_paper_t.blanks_test
     *
     * @param blanks_test the value for offline_test_paper_t.blanks_test
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    public void setBlanks_test(String blanks_test) {
        this.blanks_test = blanks_test;
    }

    @Override
    public String toString() {
        return "OfflineTestPaperT{" +
                "paper_id=" + paper_id +
                ", test_id=" + test_id +
                ", total_score=" + total_score +
                ", single_choose_score=" + single_choose_score +
                ", multi_choice_score=" + multi_choice_score +
                ", judge_score=" + judge_score +
                ", question_score=" + question_score +
                ", blanks_test_score=" + blanks_test_score +
                ", single_choose_num=" + single_choose_num +
                ", multi_choice_num=" + multi_choice_num +
                ", judge_num=" + judge_num +
                ", question_num=" + question_num +
                ", blanks_test_num=" + blanks_test_num +
                ", single_choose='" + single_choose + '\'' +
                ", multi_choice='" + multi_choice + '\'' +
                ", judge='" + judge + '\'' +
                ", question='" + question + '\'' +
                ", blanks_test='" + blanks_test + '\'' +
                '}';
    }
}