package com.kuangshan.riskcontrol.model;

import java.math.BigDecimal;

public class ParameterT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter_t.ParameterID
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    private Integer parameterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter_t.ParameterItem
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    private String parameteritem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter_t.ParameterName
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    private String parametername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter_t.ParameterValue
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    private double parametervalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter_t.ParameterID
     *
     * @return the value of parameter_t.ParameterID
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public Integer getParameterid() {
        return parameterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter_t.ParameterID
     *
     * @param parameterid the value for parameter_t.ParameterID
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public void setParameterid(Integer parameterid) {
        this.parameterid = parameterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter_t.ParameterItem
     *
     * @return the value of parameter_t.ParameterItem
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public String getParameteritem() {
        return parameteritem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter_t.ParameterItem
     *
     * @param parameteritem the value for parameter_t.ParameterItem
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public void setParameteritem(String parameteritem) {
        this.parameteritem = parameteritem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter_t.ParameterName
     *
     * @return the value of parameter_t.ParameterName
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public String getParametername() {
        return parametername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter_t.ParameterName
     *
     * @param parametername the value for parameter_t.ParameterName
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public void setParametername(String parametername) {
        this.parametername = parametername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter_t.ParameterValue
     *
     * @return the value of parameter_t.ParameterValue
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public double getParametervalue() {
        return parametervalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter_t.ParameterValue
     *
     * @param parametervalue the value for parameter_t.ParameterValue
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public void setParametervalue(double parametervalue) {
        this.parametervalue = parametervalue;
    }
}