package com.kuangshan.riskcontrol.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ParameterTExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public ParameterTExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andParameteridIsNull() {
            addCriterion("ParameterID is null");
            return (Criteria) this;
        }

        public Criteria andParameteridIsNotNull() {
            addCriterion("ParameterID is not null");
            return (Criteria) this;
        }

        public Criteria andParameteridEqualTo(Integer value) {
            addCriterion("ParameterID =", value, "parameterid");
            return (Criteria) this;
        }

        public Criteria andParameteridNotEqualTo(Integer value) {
            addCriterion("ParameterID <>", value, "parameterid");
            return (Criteria) this;
        }

        public Criteria andParameteridGreaterThan(Integer value) {
            addCriterion("ParameterID >", value, "parameterid");
            return (Criteria) this;
        }

        public Criteria andParameteridGreaterThanOrEqualTo(Integer value) {
            addCriterion("ParameterID >=", value, "parameterid");
            return (Criteria) this;
        }

        public Criteria andParameteridLessThan(Integer value) {
            addCriterion("ParameterID <", value, "parameterid");
            return (Criteria) this;
        }

        public Criteria andParameteridLessThanOrEqualTo(Integer value) {
            addCriterion("ParameterID <=", value, "parameterid");
            return (Criteria) this;
        }

        public Criteria andParameteridIn(List<Integer> values) {
            addCriterion("ParameterID in", values, "parameterid");
            return (Criteria) this;
        }

        public Criteria andParameteridNotIn(List<Integer> values) {
            addCriterion("ParameterID not in", values, "parameterid");
            return (Criteria) this;
        }

        public Criteria andParameteridBetween(Integer value1, Integer value2) {
            addCriterion("ParameterID between", value1, value2, "parameterid");
            return (Criteria) this;
        }

        public Criteria andParameteridNotBetween(Integer value1, Integer value2) {
            addCriterion("ParameterID not between", value1, value2, "parameterid");
            return (Criteria) this;
        }

        public Criteria andParameteritemIsNull() {
            addCriterion("ParameterItem is null");
            return (Criteria) this;
        }

        public Criteria andParameteritemIsNotNull() {
            addCriterion("ParameterItem is not null");
            return (Criteria) this;
        }

        public Criteria andParameteritemEqualTo(String value) {
            addCriterion("ParameterItem =", value, "parameteritem");
            return (Criteria) this;
        }

        public Criteria andParameteritemNotEqualTo(String value) {
            addCriterion("ParameterItem <>", value, "parameteritem");
            return (Criteria) this;
        }

        public Criteria andParameteritemGreaterThan(String value) {
            addCriterion("ParameterItem >", value, "parameteritem");
            return (Criteria) this;
        }

        public Criteria andParameteritemGreaterThanOrEqualTo(String value) {
            addCriterion("ParameterItem >=", value, "parameteritem");
            return (Criteria) this;
        }

        public Criteria andParameteritemLessThan(String value) {
            addCriterion("ParameterItem <", value, "parameteritem");
            return (Criteria) this;
        }

        public Criteria andParameteritemLessThanOrEqualTo(String value) {
            addCriterion("ParameterItem <=", value, "parameteritem");
            return (Criteria) this;
        }

        public Criteria andParameteritemLike(String value) {
            addCriterion("ParameterItem like", value, "parameteritem");
            return (Criteria) this;
        }

        public Criteria andParameteritemNotLike(String value) {
            addCriterion("ParameterItem not like", value, "parameteritem");
            return (Criteria) this;
        }

        public Criteria andParameteritemIn(List<String> values) {
            addCriterion("ParameterItem in", values, "parameteritem");
            return (Criteria) this;
        }

        public Criteria andParameteritemNotIn(List<String> values) {
            addCriterion("ParameterItem not in", values, "parameteritem");
            return (Criteria) this;
        }

        public Criteria andParameteritemBetween(String value1, String value2) {
            addCriterion("ParameterItem between", value1, value2, "parameteritem");
            return (Criteria) this;
        }

        public Criteria andParameteritemNotBetween(String value1, String value2) {
            addCriterion("ParameterItem not between", value1, value2, "parameteritem");
            return (Criteria) this;
        }

        public Criteria andParameternameIsNull() {
            addCriterion("ParameterName is null");
            return (Criteria) this;
        }

        public Criteria andParameternameIsNotNull() {
            addCriterion("ParameterName is not null");
            return (Criteria) this;
        }

        public Criteria andParameternameEqualTo(String value) {
            addCriterion("ParameterName =", value, "parametername");
            return (Criteria) this;
        }

        public Criteria andParameternameNotEqualTo(String value) {
            addCriterion("ParameterName <>", value, "parametername");
            return (Criteria) this;
        }

        public Criteria andParameternameGreaterThan(String value) {
            addCriterion("ParameterName >", value, "parametername");
            return (Criteria) this;
        }

        public Criteria andParameternameGreaterThanOrEqualTo(String value) {
            addCriterion("ParameterName >=", value, "parametername");
            return (Criteria) this;
        }

        public Criteria andParameternameLessThan(String value) {
            addCriterion("ParameterName <", value, "parametername");
            return (Criteria) this;
        }

        public Criteria andParameternameLessThanOrEqualTo(String value) {
            addCriterion("ParameterName <=", value, "parametername");
            return (Criteria) this;
        }

        public Criteria andParameternameLike(String value) {
            addCriterion("ParameterName like", value, "parametername");
            return (Criteria) this;
        }

        public Criteria andParameternameNotLike(String value) {
            addCriterion("ParameterName not like", value, "parametername");
            return (Criteria) this;
        }

        public Criteria andParameternameIn(List<String> values) {
            addCriterion("ParameterName in", values, "parametername");
            return (Criteria) this;
        }

        public Criteria andParameternameNotIn(List<String> values) {
            addCriterion("ParameterName not in", values, "parametername");
            return (Criteria) this;
        }

        public Criteria andParameternameBetween(String value1, String value2) {
            addCriterion("ParameterName between", value1, value2, "parametername");
            return (Criteria) this;
        }

        public Criteria andParameternameNotBetween(String value1, String value2) {
            addCriterion("ParameterName not between", value1, value2, "parametername");
            return (Criteria) this;
        }

        public Criteria andParametervalueIsNull() {
            addCriterion("ParameterValue is null");
            return (Criteria) this;
        }

        public Criteria andParametervalueIsNotNull() {
            addCriterion("ParameterValue is not null");
            return (Criteria) this;
        }

        public Criteria andParametervalueEqualTo(BigDecimal value) {
            addCriterion("ParameterValue =", value, "parametervalue");
            return (Criteria) this;
        }

        public Criteria andParametervalueNotEqualTo(BigDecimal value) {
            addCriterion("ParameterValue <>", value, "parametervalue");
            return (Criteria) this;
        }

        public Criteria andParametervalueGreaterThan(BigDecimal value) {
            addCriterion("ParameterValue >", value, "parametervalue");
            return (Criteria) this;
        }

        public Criteria andParametervalueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ParameterValue >=", value, "parametervalue");
            return (Criteria) this;
        }

        public Criteria andParametervalueLessThan(BigDecimal value) {
            addCriterion("ParameterValue <", value, "parametervalue");
            return (Criteria) this;
        }

        public Criteria andParametervalueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ParameterValue <=", value, "parametervalue");
            return (Criteria) this;
        }

        public Criteria andParametervalueIn(List<BigDecimal> values) {
            addCriterion("ParameterValue in", values, "parametervalue");
            return (Criteria) this;
        }

        public Criteria andParametervalueNotIn(List<BigDecimal> values) {
            addCriterion("ParameterValue not in", values, "parametervalue");
            return (Criteria) this;
        }

        public Criteria andParametervalueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ParameterValue between", value1, value2, "parametervalue");
            return (Criteria) this;
        }

        public Criteria andParametervalueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ParameterValue not between", value1, value2, "parametervalue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parameter_t
     *
     * @mbg.generated do_not_delete_during_merge Sun Oct 14 11:04:55 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parameter_t
     *
     * @mbg.generated Sun Oct 14 11:04:55 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}