package com.kuangshan.riskcontrol.model;

public class ResourceContentT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_content_t.res_content_id
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    private Integer res_content_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_content_t.edu_resource_id
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    private Integer edu_resource_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_content_t.upload_file_name
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    private String upload_file_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_content_t.content_credit
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    private Integer content_credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_content_t.min_learning_time
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    private Integer min_learning_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_content_t.res_content_id
     *
     * @return the value of resource_content_t.res_content_id
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public Integer getRes_content_id() {
        return res_content_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_content_t.res_content_id
     *
     * @param res_content_id the value for resource_content_t.res_content_id
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public void setRes_content_id(Integer res_content_id) {
        this.res_content_id = res_content_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_content_t.edu_resource_id
     *
     * @return the value of resource_content_t.edu_resource_id
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public Integer getEdu_resource_id() {
        return edu_resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_content_t.edu_resource_id
     *
     * @param edu_resource_id the value for resource_content_t.edu_resource_id
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public void setEdu_resource_id(Integer edu_resource_id) {
        this.edu_resource_id = edu_resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_content_t.upload_file_name
     *
     * @return the value of resource_content_t.upload_file_name
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public String getUpload_file_name() {
        return upload_file_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_content_t.upload_file_name
     *
     * @param upload_file_name the value for resource_content_t.upload_file_name
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public void setUpload_file_name(String upload_file_name) {
        this.upload_file_name = upload_file_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_content_t.content_credit
     *
     * @return the value of resource_content_t.content_credit
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public Integer getContent_credit() {
        return content_credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_content_t.content_credit
     *
     * @param content_credit the value for resource_content_t.content_credit
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public void setContent_credit(Integer content_credit) {
        this.content_credit = content_credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_content_t.min_learning_time
     *
     * @return the value of resource_content_t.min_learning_time
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public Integer getMin_learning_time() {
        return min_learning_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_content_t.min_learning_time
     *
     * @param min_learning_time the value for resource_content_t.min_learning_time
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public void setMin_learning_time(Integer min_learning_time) {
        this.min_learning_time = min_learning_time;
    }
}