package com.kuangshan.riskcontrol.model;

import java.util.ArrayList;
import java.util.List;

public class ResourceContentTExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public ResourceContentTExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRes_content_idIsNull() {
            addCriterion("res_content_id is null");
            return (Criteria) this;
        }

        public Criteria andRes_content_idIsNotNull() {
            addCriterion("res_content_id is not null");
            return (Criteria) this;
        }

        public Criteria andRes_content_idEqualTo(Integer value) {
            addCriterion("res_content_id =", value, "res_content_id");
            return (Criteria) this;
        }

        public Criteria andRes_content_idNotEqualTo(Integer value) {
            addCriterion("res_content_id <>", value, "res_content_id");
            return (Criteria) this;
        }

        public Criteria andRes_content_idGreaterThan(Integer value) {
            addCriterion("res_content_id >", value, "res_content_id");
            return (Criteria) this;
        }

        public Criteria andRes_content_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("res_content_id >=", value, "res_content_id");
            return (Criteria) this;
        }

        public Criteria andRes_content_idLessThan(Integer value) {
            addCriterion("res_content_id <", value, "res_content_id");
            return (Criteria) this;
        }

        public Criteria andRes_content_idLessThanOrEqualTo(Integer value) {
            addCriterion("res_content_id <=", value, "res_content_id");
            return (Criteria) this;
        }

        public Criteria andRes_content_idIn(List<Integer> values) {
            addCriterion("res_content_id in", values, "res_content_id");
            return (Criteria) this;
        }

        public Criteria andRes_content_idNotIn(List<Integer> values) {
            addCriterion("res_content_id not in", values, "res_content_id");
            return (Criteria) this;
        }

        public Criteria andRes_content_idBetween(Integer value1, Integer value2) {
            addCriterion("res_content_id between", value1, value2, "res_content_id");
            return (Criteria) this;
        }

        public Criteria andRes_content_idNotBetween(Integer value1, Integer value2) {
            addCriterion("res_content_id not between", value1, value2, "res_content_id");
            return (Criteria) this;
        }

        public Criteria andEdu_resource_idIsNull() {
            addCriterion("edu_resource_id is null");
            return (Criteria) this;
        }

        public Criteria andEdu_resource_idIsNotNull() {
            addCriterion("edu_resource_id is not null");
            return (Criteria) this;
        }

        public Criteria andEdu_resource_idEqualTo(Integer value) {
            addCriterion("edu_resource_id =", value, "edu_resource_id");
            return (Criteria) this;
        }

        public Criteria andEdu_resource_idNotEqualTo(Integer value) {
            addCriterion("edu_resource_id <>", value, "edu_resource_id");
            return (Criteria) this;
        }

        public Criteria andEdu_resource_idGreaterThan(Integer value) {
            addCriterion("edu_resource_id >", value, "edu_resource_id");
            return (Criteria) this;
        }

        public Criteria andEdu_resource_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("edu_resource_id >=", value, "edu_resource_id");
            return (Criteria) this;
        }

        public Criteria andEdu_resource_idLessThan(Integer value) {
            addCriterion("edu_resource_id <", value, "edu_resource_id");
            return (Criteria) this;
        }

        public Criteria andEdu_resource_idLessThanOrEqualTo(Integer value) {
            addCriterion("edu_resource_id <=", value, "edu_resource_id");
            return (Criteria) this;
        }

        public Criteria andEdu_resource_idIn(List<Integer> values) {
            addCriterion("edu_resource_id in", values, "edu_resource_id");
            return (Criteria) this;
        }

        public Criteria andEdu_resource_idNotIn(List<Integer> values) {
            addCriterion("edu_resource_id not in", values, "edu_resource_id");
            return (Criteria) this;
        }

        public Criteria andEdu_resource_idBetween(Integer value1, Integer value2) {
            addCriterion("edu_resource_id between", value1, value2, "edu_resource_id");
            return (Criteria) this;
        }

        public Criteria andEdu_resource_idNotBetween(Integer value1, Integer value2) {
            addCriterion("edu_resource_id not between", value1, value2, "edu_resource_id");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameIsNull() {
            addCriterion("upload_file_name is null");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameIsNotNull() {
            addCriterion("upload_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameEqualTo(String value) {
            addCriterion("upload_file_name =", value, "upload_file_name");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameNotEqualTo(String value) {
            addCriterion("upload_file_name <>", value, "upload_file_name");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameGreaterThan(String value) {
            addCriterion("upload_file_name >", value, "upload_file_name");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameGreaterThanOrEqualTo(String value) {
            addCriterion("upload_file_name >=", value, "upload_file_name");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameLessThan(String value) {
            addCriterion("upload_file_name <", value, "upload_file_name");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameLessThanOrEqualTo(String value) {
            addCriterion("upload_file_name <=", value, "upload_file_name");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameLike(String value) {
            addCriterion("upload_file_name like", value, "upload_file_name");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameNotLike(String value) {
            addCriterion("upload_file_name not like", value, "upload_file_name");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameIn(List<String> values) {
            addCriterion("upload_file_name in", values, "upload_file_name");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameNotIn(List<String> values) {
            addCriterion("upload_file_name not in", values, "upload_file_name");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameBetween(String value1, String value2) {
            addCriterion("upload_file_name between", value1, value2, "upload_file_name");
            return (Criteria) this;
        }

        public Criteria andUpload_file_nameNotBetween(String value1, String value2) {
            addCriterion("upload_file_name not between", value1, value2, "upload_file_name");
            return (Criteria) this;
        }

        public Criteria andContent_creditIsNull() {
            addCriterion("content_credit is null");
            return (Criteria) this;
        }

        public Criteria andContent_creditIsNotNull() {
            addCriterion("content_credit is not null");
            return (Criteria) this;
        }

        public Criteria andContent_creditEqualTo(Integer value) {
            addCriterion("content_credit =", value, "content_credit");
            return (Criteria) this;
        }

        public Criteria andContent_creditNotEqualTo(Integer value) {
            addCriterion("content_credit <>", value, "content_credit");
            return (Criteria) this;
        }

        public Criteria andContent_creditGreaterThan(Integer value) {
            addCriterion("content_credit >", value, "content_credit");
            return (Criteria) this;
        }

        public Criteria andContent_creditGreaterThanOrEqualTo(Integer value) {
            addCriterion("content_credit >=", value, "content_credit");
            return (Criteria) this;
        }

        public Criteria andContent_creditLessThan(Integer value) {
            addCriterion("content_credit <", value, "content_credit");
            return (Criteria) this;
        }

        public Criteria andContent_creditLessThanOrEqualTo(Integer value) {
            addCriterion("content_credit <=", value, "content_credit");
            return (Criteria) this;
        }

        public Criteria andContent_creditIn(List<Integer> values) {
            addCriterion("content_credit in", values, "content_credit");
            return (Criteria) this;
        }

        public Criteria andContent_creditNotIn(List<Integer> values) {
            addCriterion("content_credit not in", values, "content_credit");
            return (Criteria) this;
        }

        public Criteria andContent_creditBetween(Integer value1, Integer value2) {
            addCriterion("content_credit between", value1, value2, "content_credit");
            return (Criteria) this;
        }

        public Criteria andContent_creditNotBetween(Integer value1, Integer value2) {
            addCriterion("content_credit not between", value1, value2, "content_credit");
            return (Criteria) this;
        }

        public Criteria andMin_learning_timeIsNull() {
            addCriterion("min_learning_time is null");
            return (Criteria) this;
        }

        public Criteria andMin_learning_timeIsNotNull() {
            addCriterion("min_learning_time is not null");
            return (Criteria) this;
        }

        public Criteria andMin_learning_timeEqualTo(Integer value) {
            addCriterion("min_learning_time =", value, "min_learning_time");
            return (Criteria) this;
        }

        public Criteria andMin_learning_timeNotEqualTo(Integer value) {
            addCriterion("min_learning_time <>", value, "min_learning_time");
            return (Criteria) this;
        }

        public Criteria andMin_learning_timeGreaterThan(Integer value) {
            addCriterion("min_learning_time >", value, "min_learning_time");
            return (Criteria) this;
        }

        public Criteria andMin_learning_timeGreaterThanOrEqualTo(Integer value) {
            addCriterion("min_learning_time >=", value, "min_learning_time");
            return (Criteria) this;
        }

        public Criteria andMin_learning_timeLessThan(Integer value) {
            addCriterion("min_learning_time <", value, "min_learning_time");
            return (Criteria) this;
        }

        public Criteria andMin_learning_timeLessThanOrEqualTo(Integer value) {
            addCriterion("min_learning_time <=", value, "min_learning_time");
            return (Criteria) this;
        }

        public Criteria andMin_learning_timeIn(List<Integer> values) {
            addCriterion("min_learning_time in", values, "min_learning_time");
            return (Criteria) this;
        }

        public Criteria andMin_learning_timeNotIn(List<Integer> values) {
            addCriterion("min_learning_time not in", values, "min_learning_time");
            return (Criteria) this;
        }

        public Criteria andMin_learning_timeBetween(Integer value1, Integer value2) {
            addCriterion("min_learning_time between", value1, value2, "min_learning_time");
            return (Criteria) this;
        }

        public Criteria andMin_learning_timeNotBetween(Integer value1, Integer value2) {
            addCriterion("min_learning_time not between", value1, value2, "min_learning_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resource_content_t
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 19 20:23:56 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}