package com.kuangshan.riskcontrol.model;

import java.math.BigDecimal;
import java.util.Date;

public class RollEducationT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_education_t.roll_education_id
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    private Integer roll_education_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_education_t.employee_num
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    private String employee_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_education_t.education_id
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    private Integer education_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_education_t.test_id
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    private Integer test_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_education_t.examinee_pwd
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    private String examinee_pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_education_t.score
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_education_t.test_submit_time
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    private Date test_submit_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_education_t.makeup_grade
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    private BigDecimal makeup_grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_education_t.makeup_submit_time
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    private Date makeup_submit_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_education_t.score_mode
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    private String score_mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_education_t.is_finished
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    private Integer is_finished;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_education_t.roll_education_id
     *
     * @return the value of roll_education_t.roll_education_id
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public Integer getRoll_education_id() {
        return roll_education_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_education_t.roll_education_id
     *
     * @param roll_education_id the value for roll_education_t.roll_education_id
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public void setRoll_education_id(Integer roll_education_id) {
        this.roll_education_id = roll_education_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_education_t.employee_num
     *
     * @return the value of roll_education_t.employee_num
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public String getEmployee_num() {
        return employee_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_education_t.employee_num
     *
     * @param employee_num the value for roll_education_t.employee_num
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public void setEmployee_num(String employee_num) {
        this.employee_num = employee_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_education_t.education_id
     *
     * @return the value of roll_education_t.education_id
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public Integer getEducation_id() {
        return education_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_education_t.education_id
     *
     * @param education_id the value for roll_education_t.education_id
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public void setEducation_id(Integer education_id) {
        this.education_id = education_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_education_t.test_id
     *
     * @return the value of roll_education_t.test_id
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public Integer getTest_id() {
        return test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_education_t.test_id
     *
     * @param test_id the value for roll_education_t.test_id
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public void setTest_id(Integer test_id) {
        this.test_id = test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_education_t.examinee_pwd
     *
     * @return the value of roll_education_t.examinee_pwd
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public String getExaminee_pwd() {
        return examinee_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_education_t.examinee_pwd
     *
     * @param examinee_pwd the value for roll_education_t.examinee_pwd
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public void setExaminee_pwd(String examinee_pwd) {
        this.examinee_pwd = examinee_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_education_t.score
     *
     * @return the value of roll_education_t.score
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_education_t.score
     *
     * @param score the value for roll_education_t.score
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_education_t.test_submit_time
     *
     * @return the value of roll_education_t.test_submit_time
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public Date getTest_submit_time() {
        return test_submit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_education_t.test_submit_time
     *
     * @param test_submit_time the value for roll_education_t.test_submit_time
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public void setTest_submit_time(Date test_submit_time) {
        this.test_submit_time = test_submit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_education_t.makeup_grade
     *
     * @return the value of roll_education_t.makeup_grade
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public BigDecimal getMakeup_grade() {
        return makeup_grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_education_t.makeup_grade
     *
     * @param makeup_grade the value for roll_education_t.makeup_grade
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public void setMakeup_grade(BigDecimal makeup_grade) {
        this.makeup_grade = makeup_grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_education_t.makeup_submit_time
     *
     * @return the value of roll_education_t.makeup_submit_time
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public Date getMakeup_submit_time() {
        return makeup_submit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_education_t.makeup_submit_time
     *
     * @param makeup_submit_time the value for roll_education_t.makeup_submit_time
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public void setMakeup_submit_time(Date makeup_submit_time) {
        this.makeup_submit_time = makeup_submit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_education_t.score_mode
     *
     * @return the value of roll_education_t.score_mode
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public String getScore_mode() {
        return score_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_education_t.score_mode
     *
     * @param score_mode the value for roll_education_t.score_mode
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public void setScore_mode(String score_mode) {
        this.score_mode = score_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_education_t.is_finished
     *
     * @return the value of roll_education_t.is_finished
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public Integer getIs_finished() {
        return is_finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_education_t.is_finished
     *
     * @param is_finished the value for roll_education_t.is_finished
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    public void setIs_finished(Integer is_finished) {
        this.is_finished = is_finished;
    }
}