package com.kuangshan.riskcontrol.model;

import java.util.Date;

public class TestInfoT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.test_id
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private Integer test_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.education_id
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private Integer education_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.test_name
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private String test_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.edu_category_id
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private Integer edu_category_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.test_address
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private String test_address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.test_start_time
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private Date test_start_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.test_end_time
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private Date test_end_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.related_test_id
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private Integer related_test_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.test_type
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private String test_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.score_mode
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private String score_mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.is_online
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private String is_online;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.is_released
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private String is_released;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.test_time
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private Integer test_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info_t.is_submitted
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    private Integer is_submitted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.test_id
     *
     * @return the value of test_info_t.test_id
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public Integer getTest_id() {
        return test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.test_id
     *
     * @param test_id the value for test_info_t.test_id
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setTest_id(Integer test_id) {
        this.test_id = test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.education_id
     *
     * @return the value of test_info_t.education_id
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public Integer getEducation_id() {
        return education_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.education_id
     *
     * @param education_id the value for test_info_t.education_id
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setEducation_id(Integer education_id) {
        this.education_id = education_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.test_name
     *
     * @return the value of test_info_t.test_name
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public String getTest_name() {
        return test_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.test_name
     *
     * @param test_name the value for test_info_t.test_name
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setTest_name(String test_name) {
        this.test_name = test_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.edu_category_id
     *
     * @return the value of test_info_t.edu_category_id
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public Integer getEdu_category_id() {
        return edu_category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.edu_category_id
     *
     * @param edu_category_id the value for test_info_t.edu_category_id
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setEdu_category_id(Integer edu_category_id) {
        this.edu_category_id = edu_category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.test_address
     *
     * @return the value of test_info_t.test_address
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public String getTest_address() {
        return test_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.test_address
     *
     * @param test_address the value for test_info_t.test_address
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setTest_address(String test_address) {
        this.test_address = test_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.test_start_time
     *
     * @return the value of test_info_t.test_start_time
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public Date getTest_start_time() {
        return test_start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.test_start_time
     *
     * @param test_start_time the value for test_info_t.test_start_time
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setTest_start_time(Date test_start_time) {
        this.test_start_time = test_start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.test_end_time
     *
     * @return the value of test_info_t.test_end_time
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public Date getTest_end_time() {
        return test_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.test_end_time
     *
     * @param test_end_time the value for test_info_t.test_end_time
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setTest_end_time(Date test_end_time) {
        this.test_end_time = test_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.related_test_id
     *
     * @return the value of test_info_t.related_test_id
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public Integer getRelated_test_id() {
        return related_test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.related_test_id
     *
     * @param related_test_id the value for test_info_t.related_test_id
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setRelated_test_id(Integer related_test_id) {
        this.related_test_id = related_test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.test_type
     *
     * @return the value of test_info_t.test_type
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public String getTest_type() {
        return test_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.test_type
     *
     * @param test_type the value for test_info_t.test_type
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setTest_type(String test_type) {
        this.test_type = test_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.score_mode
     *
     * @return the value of test_info_t.score_mode
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public String getScore_mode() {
        return score_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.score_mode
     *
     * @param score_mode the value for test_info_t.score_mode
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setScore_mode(String score_mode) {
        this.score_mode = score_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.is_online
     *
     * @return the value of test_info_t.is_online
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public String getIs_online() {
        return is_online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.is_online
     *
     * @param is_online the value for test_info_t.is_online
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setIs_online(String is_online) {
        this.is_online = is_online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.is_released
     *
     * @return the value of test_info_t.is_released
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public String getIs_released() {
        return is_released;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.is_released
     *
     * @param is_released the value for test_info_t.is_released
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setIs_released(String is_released) {
        this.is_released = is_released;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.test_time
     *
     * @return the value of test_info_t.test_time
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public Integer getTest_time() {
        return test_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.test_time
     *
     * @param test_time the value for test_info_t.test_time
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setTest_time(Integer test_time) {
        this.test_time = test_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info_t.is_submitted
     *
     * @return the value of test_info_t.is_submitted
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public Integer getIs_submitted() {
        return is_submitted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info_t.is_submitted
     *
     * @param is_submitted the value for test_info_t.is_submitted
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setIs_submitted(Integer is_submitted) {
        this.is_submitted = is_submitted;
    }
}