package com.kuangshan.riskcontrol.model;

import java.math.BigDecimal;

public class TestScoreT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.test_score_id
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private Integer test_score_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.test_id
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private Integer test_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.employee_num
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private String employee_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.paper_score
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private BigDecimal paper_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.single_choose_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private String single_choose_answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.single_choose_score
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private BigDecimal single_choose_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.multi_choice_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private String multi_choice_answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.multi_choice_score
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private BigDecimal multi_choice_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.judge_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private String judge_answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.judge_score
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private BigDecimal judge_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.question_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private String question_answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.question_source
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private BigDecimal question_source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.blanks_test_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private String blanks_test_answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.blanks_test_source
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private BigDecimal blanks_test_source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_score_t.finished
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    private String finished;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.test_score_id
     *
     * @return the value of test_score_t.test_score_id
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public Integer getTest_score_id() {
        return test_score_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.test_score_id
     *
     * @param test_score_id the value for test_score_t.test_score_id
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setTest_score_id(Integer test_score_id) {
        this.test_score_id = test_score_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.test_id
     *
     * @return the value of test_score_t.test_id
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public Integer getTest_id() {
        return test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.test_id
     *
     * @param test_id the value for test_score_t.test_id
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setTest_id(Integer test_id) {
        this.test_id = test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.employee_num
     *
     * @return the value of test_score_t.employee_num
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public String getEmployee_num() {
        return employee_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.employee_num
     *
     * @param employee_num the value for test_score_t.employee_num
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setEmployee_num(String employee_num) {
        this.employee_num = employee_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.paper_score
     *
     * @return the value of test_score_t.paper_score
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public BigDecimal getPaper_score() {
        return paper_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.paper_score
     *
     * @param paper_score the value for test_score_t.paper_score
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setPaper_score(BigDecimal paper_score) {
        this.paper_score = paper_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.single_choose_answer
     *
     * @return the value of test_score_t.single_choose_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public String getSingle_choose_answer() {
        return single_choose_answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.single_choose_answer
     *
     * @param single_choose_answer the value for test_score_t.single_choose_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setSingle_choose_answer(String single_choose_answer) {
        this.single_choose_answer = single_choose_answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.single_choose_score
     *
     * @return the value of test_score_t.single_choose_score
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public BigDecimal getSingle_choose_score() {
        return single_choose_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.single_choose_score
     *
     * @param single_choose_score the value for test_score_t.single_choose_score
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setSingle_choose_score(BigDecimal single_choose_score) {
        this.single_choose_score = single_choose_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.multi_choice_answer
     *
     * @return the value of test_score_t.multi_choice_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public String getMulti_choice_answer() {
        return multi_choice_answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.multi_choice_answer
     *
     * @param multi_choice_answer the value for test_score_t.multi_choice_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setMulti_choice_answer(String multi_choice_answer) {
        this.multi_choice_answer = multi_choice_answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.multi_choice_score
     *
     * @return the value of test_score_t.multi_choice_score
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public BigDecimal getMulti_choice_score() {
        return multi_choice_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.multi_choice_score
     *
     * @param multi_choice_score the value for test_score_t.multi_choice_score
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setMulti_choice_score(BigDecimal multi_choice_score) {
        this.multi_choice_score = multi_choice_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.judge_answer
     *
     * @return the value of test_score_t.judge_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public String getJudge_answer() {
        return judge_answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.judge_answer
     *
     * @param judge_answer the value for test_score_t.judge_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setJudge_answer(String judge_answer) {
        this.judge_answer = judge_answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.judge_score
     *
     * @return the value of test_score_t.judge_score
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public BigDecimal getJudge_score() {
        return judge_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.judge_score
     *
     * @param judge_score the value for test_score_t.judge_score
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setJudge_score(BigDecimal judge_score) {
        this.judge_score = judge_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.question_answer
     *
     * @return the value of test_score_t.question_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public String getQuestion_answer() {
        return question_answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.question_answer
     *
     * @param question_answer the value for test_score_t.question_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setQuestion_answer(String question_answer) {
        this.question_answer = question_answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.question_source
     *
     * @return the value of test_score_t.question_source
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public BigDecimal getQuestion_source() {
        return question_source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.question_source
     *
     * @param question_source the value for test_score_t.question_source
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setQuestion_source(BigDecimal question_source) {
        this.question_source = question_source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.blanks_test_answer
     *
     * @return the value of test_score_t.blanks_test_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public String getBlanks_test_answer() {
        return blanks_test_answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.blanks_test_answer
     *
     * @param blanks_test_answer the value for test_score_t.blanks_test_answer
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setBlanks_test_answer(String blanks_test_answer) {
        this.blanks_test_answer = blanks_test_answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.blanks_test_source
     *
     * @return the value of test_score_t.blanks_test_source
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public BigDecimal getBlanks_test_source() {
        return blanks_test_source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.blanks_test_source
     *
     * @param blanks_test_source the value for test_score_t.blanks_test_source
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setBlanks_test_source(BigDecimal blanks_test_source) {
        this.blanks_test_source = blanks_test_source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_score_t.finished
     *
     * @return the value of test_score_t.finished
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public String getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_score_t.finished
     *
     * @param finished the value for test_score_t.finished
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setFinished(String finished) {
        this.finished = finished;
    }
}