package com.kuangshan.riskcontrol.model;

public class TestMultiChoiceT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_multi_choice_t.multi_choice_id
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    private Integer multi_choice_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_multi_choice_t.edu_category_id
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    private Integer edu_category_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_multi_choice_t.edu_knowledge_point_id
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    private Integer edu_knowledge_point_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_multi_choice_t.multi_choice_content
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    private String multi_choice_content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_multi_choice_t.multi_choice_a
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    private String multi_choice_a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_multi_choice_t.multi_choice_b
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    private String multi_choice_b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_multi_choice_t.multi_choice_c
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    private String multi_choice_c;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_multi_choice_t.multi_choice_d
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    private String multi_choice_d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_multi_choice_t.answer
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    private String answer;


    private Integer deleted;

    private String explanation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_multi_choice_t.multi_choice_id
     *
     * @return the value of test_multi_choice_t.multi_choice_id
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public Integer getMulti_choice_id() {
        return multi_choice_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_multi_choice_t.multi_choice_id
     *
     * @param multi_choice_id the value for test_multi_choice_t.multi_choice_id
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public void setMulti_choice_id(Integer multi_choice_id) {
        this.multi_choice_id = multi_choice_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_multi_choice_t.edu_category_id
     *
     * @return the value of test_multi_choice_t.edu_category_id
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public Integer getEdu_category_id() {
        return edu_category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_multi_choice_t.edu_category_id
     *
     * @param edu_category_id the value for test_multi_choice_t.edu_category_id
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public void setEdu_category_id(Integer edu_category_id) {
        this.edu_category_id = edu_category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_multi_choice_t.edu_knowledge_point_id
     *
     * @return the value of test_multi_choice_t.edu_knowledge_point_id
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public Integer getEdu_knowledge_point_id() {
        return edu_knowledge_point_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_multi_choice_t.edu_knowledge_point_id
     *
     * @param edu_knowledge_point_id the value for test_multi_choice_t.edu_knowledge_point_id
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public void setEdu_knowledge_point_id(Integer edu_knowledge_point_id) {
        this.edu_knowledge_point_id = edu_knowledge_point_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_multi_choice_t.multi_choice_content
     *
     * @return the value of test_multi_choice_t.multi_choice_content
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public String getMulti_choice_content() {
        return multi_choice_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_multi_choice_t.multi_choice_content
     *
     * @param multi_choice_content the value for test_multi_choice_t.multi_choice_content
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public void setMulti_choice_content(String multi_choice_content) {
        this.multi_choice_content = multi_choice_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_multi_choice_t.multi_choice_a
     *
     * @return the value of test_multi_choice_t.multi_choice_a
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public String getMulti_choice_a() {
        return multi_choice_a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_multi_choice_t.multi_choice_a
     *
     * @param multi_choice_a the value for test_multi_choice_t.multi_choice_a
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public void setMulti_choice_a(String multi_choice_a) {
        this.multi_choice_a = multi_choice_a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_multi_choice_t.multi_choice_b
     *
     * @return the value of test_multi_choice_t.multi_choice_b
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public String getMulti_choice_b() {
        return multi_choice_b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_multi_choice_t.multi_choice_b
     *
     * @param multi_choice_b the value for test_multi_choice_t.multi_choice_b
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public void setMulti_choice_b(String multi_choice_b) {
        this.multi_choice_b = multi_choice_b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_multi_choice_t.multi_choice_c
     *
     * @return the value of test_multi_choice_t.multi_choice_c
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public String getMulti_choice_c() {
        return multi_choice_c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_multi_choice_t.multi_choice_c
     *
     * @param multi_choice_c the value for test_multi_choice_t.multi_choice_c
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public void setMulti_choice_c(String multi_choice_c) {
        this.multi_choice_c = multi_choice_c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_multi_choice_t.multi_choice_d
     *
     * @return the value of test_multi_choice_t.multi_choice_d
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public String getMulti_choice_d() {
        return multi_choice_d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_multi_choice_t.multi_choice_d
     *
     * @param multi_choice_d the value for test_multi_choice_t.multi_choice_d
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public void setMulti_choice_d(String multi_choice_d) {
        this.multi_choice_d = multi_choice_d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_multi_choice_t.answer
     *
     * @return the value of test_multi_choice_t.answer
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_multi_choice_t.answer
     *
     * @param answer the value for test_multi_choice_t.answer
     *
     * @mbg.generated Sat Feb 01 14:34:26 CST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }


    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    public String getExplanation() {
        return explanation;
    }

    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }


    @Override
    public String toString() {
        return "TestMultiChoiceT{" +
                "multi_choice_id=" + multi_choice_id +
                ", edu_category_id=" + edu_category_id +
                ", edu_knowledge_point_id=" + edu_knowledge_point_id +
                ", multi_choice_content='" + multi_choice_content + '\'' +
                ", multi_choice_a='" + multi_choice_a + '\'' +
                ", multi_choice_b='" + multi_choice_b + '\'' +
                ", multi_choice_c='" + multi_choice_c + '\'' +
                ", multi_choice_d='" + multi_choice_d + '\'' +
                ", answer='" + answer + '\'' +
                ", deleted=" + deleted +
                ", explanation='" + explanation + '\'' +
                '}';
    }


}