package com.kuangshan.riskcontrol.model;

public class TestQuestionAndAnswerT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_question_and_answer_t.question_id
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    private Integer question_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_question_and_answer_t.edu_category_id
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    private Integer edu_category_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_question_and_answer_t.edu_knowledge_point_id
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    private Integer edu_knowledge_point_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_question_and_answer_t.question_content
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    private String question_content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_question_and_answer_t.answer
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    private String answer;


    private Integer deleted;


    private String explanation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_question_and_answer_t.question_id
     *
     * @return the value of test_question_and_answer_t.question_id
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    public Integer getQuestion_id() {
        return question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_question_and_answer_t.question_id
     *
     * @param question_id the value for test_question_and_answer_t.question_id
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    public void setQuestion_id(Integer question_id) {
        this.question_id = question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_question_and_answer_t.edu_category_id
     *
     * @return the value of test_question_and_answer_t.edu_category_id
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    public Integer getEdu_category_id() {
        return edu_category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_question_and_answer_t.edu_category_id
     *
     * @param edu_category_id the value for test_question_and_answer_t.edu_category_id
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    public void setEdu_category_id(Integer edu_category_id) {
        this.edu_category_id = edu_category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_question_and_answer_t.edu_knowledge_point_id
     *
     * @return the value of test_question_and_answer_t.edu_knowledge_point_id
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    public Integer getEdu_knowledge_point_id() {
        return edu_knowledge_point_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_question_and_answer_t.edu_knowledge_point_id
     *
     * @param edu_knowledge_point_id the value for test_question_and_answer_t.edu_knowledge_point_id
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    public void setEdu_knowledge_point_id(Integer edu_knowledge_point_id) {
        this.edu_knowledge_point_id = edu_knowledge_point_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_question_and_answer_t.question_content
     *
     * @return the value of test_question_and_answer_t.question_content
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    public String getQuestion_content() {
        return question_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_question_and_answer_t.question_content
     *
     * @param question_content the value for test_question_and_answer_t.question_content
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    public void setQuestion_content(String question_content) {
        this.question_content = question_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_question_and_answer_t.answer
     *
     * @return the value of test_question_and_answer_t.answer
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_question_and_answer_t.answer
     *
     * @param answer the value for test_question_and_answer_t.answer
     *
     * @mbg.generated Sat Feb 01 14:35:46 CST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }


    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }


    public String getExplanation() {
        return explanation;
    }

    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }

    @Override
    public String toString() {
        return "TestQuestionAndAnswerT{" +
                "question_id=" + question_id +
                ", edu_category_id=" + edu_category_id +
                ", edu_knowledge_point_id=" + edu_knowledge_point_id +
                ", question_content='" + question_content + '\'' +
                ", answer='" + answer + '\'' +
                ", deleted=" + deleted +
                ", explanation='" + explanation + '\'' +
                '}';
    }

}