package com.kuangshan.riskcontrol.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TestScoreTExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public TestScoreTExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTest_score_idIsNull() {
            addCriterion("test_score_id is null");
            return (Criteria) this;
        }

        public Criteria andTest_score_idIsNotNull() {
            addCriterion("test_score_id is not null");
            return (Criteria) this;
        }

        public Criteria andTest_score_idEqualTo(Integer value) {
            addCriterion("test_score_id =", value, "test_score_id");
            return (Criteria) this;
        }

        public Criteria andTest_score_idNotEqualTo(Integer value) {
            addCriterion("test_score_id <>", value, "test_score_id");
            return (Criteria) this;
        }

        public Criteria andTest_score_idGreaterThan(Integer value) {
            addCriterion("test_score_id >", value, "test_score_id");
            return (Criteria) this;
        }

        public Criteria andTest_score_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_score_id >=", value, "test_score_id");
            return (Criteria) this;
        }

        public Criteria andTest_score_idLessThan(Integer value) {
            addCriterion("test_score_id <", value, "test_score_id");
            return (Criteria) this;
        }

        public Criteria andTest_score_idLessThanOrEqualTo(Integer value) {
            addCriterion("test_score_id <=", value, "test_score_id");
            return (Criteria) this;
        }

        public Criteria andTest_score_idIn(List<Integer> values) {
            addCriterion("test_score_id in", values, "test_score_id");
            return (Criteria) this;
        }

        public Criteria andTest_score_idNotIn(List<Integer> values) {
            addCriterion("test_score_id not in", values, "test_score_id");
            return (Criteria) this;
        }

        public Criteria andTest_score_idBetween(Integer value1, Integer value2) {
            addCriterion("test_score_id between", value1, value2, "test_score_id");
            return (Criteria) this;
        }

        public Criteria andTest_score_idNotBetween(Integer value1, Integer value2) {
            addCriterion("test_score_id not between", value1, value2, "test_score_id");
            return (Criteria) this;
        }

        public Criteria andTest_idIsNull() {
            addCriterion("test_id is null");
            return (Criteria) this;
        }

        public Criteria andTest_idIsNotNull() {
            addCriterion("test_id is not null");
            return (Criteria) this;
        }

        public Criteria andTest_idEqualTo(Integer value) {
            addCriterion("test_id =", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idNotEqualTo(Integer value) {
            addCriterion("test_id <>", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idGreaterThan(Integer value) {
            addCriterion("test_id >", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_id >=", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idLessThan(Integer value) {
            addCriterion("test_id <", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idLessThanOrEqualTo(Integer value) {
            addCriterion("test_id <=", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idIn(List<Integer> values) {
            addCriterion("test_id in", values, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idNotIn(List<Integer> values) {
            addCriterion("test_id not in", values, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idBetween(Integer value1, Integer value2) {
            addCriterion("test_id between", value1, value2, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idNotBetween(Integer value1, Integer value2) {
            addCriterion("test_id not between", value1, value2, "test_id");
            return (Criteria) this;
        }

        public Criteria andEmployee_numIsNull() {
            addCriterion("employee_num is null");
            return (Criteria) this;
        }

        public Criteria andEmployee_numIsNotNull() {
            addCriterion("employee_num is not null");
            return (Criteria) this;
        }

        public Criteria andEmployee_numEqualTo(String value) {
            addCriterion("employee_num =", value, "employee_num");
            return (Criteria) this;
        }

        public Criteria andEmployee_numNotEqualTo(String value) {
            addCriterion("employee_num <>", value, "employee_num");
            return (Criteria) this;
        }

        public Criteria andEmployee_numGreaterThan(String value) {
            addCriterion("employee_num >", value, "employee_num");
            return (Criteria) this;
        }

        public Criteria andEmployee_numGreaterThanOrEqualTo(String value) {
            addCriterion("employee_num >=", value, "employee_num");
            return (Criteria) this;
        }

        public Criteria andEmployee_numLessThan(String value) {
            addCriterion("employee_num <", value, "employee_num");
            return (Criteria) this;
        }

        public Criteria andEmployee_numLessThanOrEqualTo(String value) {
            addCriterion("employee_num <=", value, "employee_num");
            return (Criteria) this;
        }

        public Criteria andEmployee_numLike(String value) {
            addCriterion("employee_num like", value, "employee_num");
            return (Criteria) this;
        }

        public Criteria andEmployee_numNotLike(String value) {
            addCriterion("employee_num not like", value, "employee_num");
            return (Criteria) this;
        }

        public Criteria andEmployee_numIn(List<String> values) {
            addCriterion("employee_num in", values, "employee_num");
            return (Criteria) this;
        }

        public Criteria andEmployee_numNotIn(List<String> values) {
            addCriterion("employee_num not in", values, "employee_num");
            return (Criteria) this;
        }

        public Criteria andEmployee_numBetween(String value1, String value2) {
            addCriterion("employee_num between", value1, value2, "employee_num");
            return (Criteria) this;
        }

        public Criteria andEmployee_numNotBetween(String value1, String value2) {
            addCriterion("employee_num not between", value1, value2, "employee_num");
            return (Criteria) this;
        }

        public Criteria andPaper_scoreIsNull() {
            addCriterion("paper_score is null");
            return (Criteria) this;
        }

        public Criteria andPaper_scoreIsNotNull() {
            addCriterion("paper_score is not null");
            return (Criteria) this;
        }

        public Criteria andPaper_scoreEqualTo(BigDecimal value) {
            addCriterion("paper_score =", value, "paper_score");
            return (Criteria) this;
        }

        public Criteria andPaper_scoreNotEqualTo(BigDecimal value) {
            addCriterion("paper_score <>", value, "paper_score");
            return (Criteria) this;
        }

        public Criteria andPaper_scoreGreaterThan(BigDecimal value) {
            addCriterion("paper_score >", value, "paper_score");
            return (Criteria) this;
        }

        public Criteria andPaper_scoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("paper_score >=", value, "paper_score");
            return (Criteria) this;
        }

        public Criteria andPaper_scoreLessThan(BigDecimal value) {
            addCriterion("paper_score <", value, "paper_score");
            return (Criteria) this;
        }

        public Criteria andPaper_scoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("paper_score <=", value, "paper_score");
            return (Criteria) this;
        }

        public Criteria andPaper_scoreIn(List<BigDecimal> values) {
            addCriterion("paper_score in", values, "paper_score");
            return (Criteria) this;
        }

        public Criteria andPaper_scoreNotIn(List<BigDecimal> values) {
            addCriterion("paper_score not in", values, "paper_score");
            return (Criteria) this;
        }

        public Criteria andPaper_scoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paper_score between", value1, value2, "paper_score");
            return (Criteria) this;
        }

        public Criteria andPaper_scoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paper_score not between", value1, value2, "paper_score");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerIsNull() {
            addCriterion("single_choose_answer is null");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerIsNotNull() {
            addCriterion("single_choose_answer is not null");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerEqualTo(String value) {
            addCriterion("single_choose_answer =", value, "single_choose_answer");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerNotEqualTo(String value) {
            addCriterion("single_choose_answer <>", value, "single_choose_answer");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerGreaterThan(String value) {
            addCriterion("single_choose_answer >", value, "single_choose_answer");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerGreaterThanOrEqualTo(String value) {
            addCriterion("single_choose_answer >=", value, "single_choose_answer");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerLessThan(String value) {
            addCriterion("single_choose_answer <", value, "single_choose_answer");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerLessThanOrEqualTo(String value) {
            addCriterion("single_choose_answer <=", value, "single_choose_answer");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerLike(String value) {
            addCriterion("single_choose_answer like", value, "single_choose_answer");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerNotLike(String value) {
            addCriterion("single_choose_answer not like", value, "single_choose_answer");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerIn(List<String> values) {
            addCriterion("single_choose_answer in", values, "single_choose_answer");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerNotIn(List<String> values) {
            addCriterion("single_choose_answer not in", values, "single_choose_answer");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerBetween(String value1, String value2) {
            addCriterion("single_choose_answer between", value1, value2, "single_choose_answer");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_answerNotBetween(String value1, String value2) {
            addCriterion("single_choose_answer not between", value1, value2, "single_choose_answer");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_scoreIsNull() {
            addCriterion("single_choose_score is null");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_scoreIsNotNull() {
            addCriterion("single_choose_score is not null");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_scoreEqualTo(BigDecimal value) {
            addCriterion("single_choose_score =", value, "single_choose_score");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_scoreNotEqualTo(BigDecimal value) {
            addCriterion("single_choose_score <>", value, "single_choose_score");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_scoreGreaterThan(BigDecimal value) {
            addCriterion("single_choose_score >", value, "single_choose_score");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_scoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("single_choose_score >=", value, "single_choose_score");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_scoreLessThan(BigDecimal value) {
            addCriterion("single_choose_score <", value, "single_choose_score");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_scoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("single_choose_score <=", value, "single_choose_score");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_scoreIn(List<BigDecimal> values) {
            addCriterion("single_choose_score in", values, "single_choose_score");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_scoreNotIn(List<BigDecimal> values) {
            addCriterion("single_choose_score not in", values, "single_choose_score");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_scoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("single_choose_score between", value1, value2, "single_choose_score");
            return (Criteria) this;
        }

        public Criteria andSingle_choose_scoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("single_choose_score not between", value1, value2, "single_choose_score");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerIsNull() {
            addCriterion("multi_choice_answer is null");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerIsNotNull() {
            addCriterion("multi_choice_answer is not null");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerEqualTo(String value) {
            addCriterion("multi_choice_answer =", value, "multi_choice_answer");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerNotEqualTo(String value) {
            addCriterion("multi_choice_answer <>", value, "multi_choice_answer");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerGreaterThan(String value) {
            addCriterion("multi_choice_answer >", value, "multi_choice_answer");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerGreaterThanOrEqualTo(String value) {
            addCriterion("multi_choice_answer >=", value, "multi_choice_answer");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerLessThan(String value) {
            addCriterion("multi_choice_answer <", value, "multi_choice_answer");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerLessThanOrEqualTo(String value) {
            addCriterion("multi_choice_answer <=", value, "multi_choice_answer");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerLike(String value) {
            addCriterion("multi_choice_answer like", value, "multi_choice_answer");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerNotLike(String value) {
            addCriterion("multi_choice_answer not like", value, "multi_choice_answer");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerIn(List<String> values) {
            addCriterion("multi_choice_answer in", values, "multi_choice_answer");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerNotIn(List<String> values) {
            addCriterion("multi_choice_answer not in", values, "multi_choice_answer");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerBetween(String value1, String value2) {
            addCriterion("multi_choice_answer between", value1, value2, "multi_choice_answer");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_answerNotBetween(String value1, String value2) {
            addCriterion("multi_choice_answer not between", value1, value2, "multi_choice_answer");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_scoreIsNull() {
            addCriterion("multi_choice_score is null");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_scoreIsNotNull() {
            addCriterion("multi_choice_score is not null");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_scoreEqualTo(BigDecimal value) {
            addCriterion("multi_choice_score =", value, "multi_choice_score");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_scoreNotEqualTo(BigDecimal value) {
            addCriterion("multi_choice_score <>", value, "multi_choice_score");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_scoreGreaterThan(BigDecimal value) {
            addCriterion("multi_choice_score >", value, "multi_choice_score");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_scoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("multi_choice_score >=", value, "multi_choice_score");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_scoreLessThan(BigDecimal value) {
            addCriterion("multi_choice_score <", value, "multi_choice_score");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_scoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("multi_choice_score <=", value, "multi_choice_score");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_scoreIn(List<BigDecimal> values) {
            addCriterion("multi_choice_score in", values, "multi_choice_score");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_scoreNotIn(List<BigDecimal> values) {
            addCriterion("multi_choice_score not in", values, "multi_choice_score");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_scoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("multi_choice_score between", value1, value2, "multi_choice_score");
            return (Criteria) this;
        }

        public Criteria andMulti_choice_scoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("multi_choice_score not between", value1, value2, "multi_choice_score");
            return (Criteria) this;
        }

        public Criteria andJudge_answerIsNull() {
            addCriterion("judge_answer is null");
            return (Criteria) this;
        }

        public Criteria andJudge_answerIsNotNull() {
            addCriterion("judge_answer is not null");
            return (Criteria) this;
        }

        public Criteria andJudge_answerEqualTo(String value) {
            addCriterion("judge_answer =", value, "judge_answer");
            return (Criteria) this;
        }

        public Criteria andJudge_answerNotEqualTo(String value) {
            addCriterion("judge_answer <>", value, "judge_answer");
            return (Criteria) this;
        }

        public Criteria andJudge_answerGreaterThan(String value) {
            addCriterion("judge_answer >", value, "judge_answer");
            return (Criteria) this;
        }

        public Criteria andJudge_answerGreaterThanOrEqualTo(String value) {
            addCriterion("judge_answer >=", value, "judge_answer");
            return (Criteria) this;
        }

        public Criteria andJudge_answerLessThan(String value) {
            addCriterion("judge_answer <", value, "judge_answer");
            return (Criteria) this;
        }

        public Criteria andJudge_answerLessThanOrEqualTo(String value) {
            addCriterion("judge_answer <=", value, "judge_answer");
            return (Criteria) this;
        }

        public Criteria andJudge_answerLike(String value) {
            addCriterion("judge_answer like", value, "judge_answer");
            return (Criteria) this;
        }

        public Criteria andJudge_answerNotLike(String value) {
            addCriterion("judge_answer not like", value, "judge_answer");
            return (Criteria) this;
        }

        public Criteria andJudge_answerIn(List<String> values) {
            addCriterion("judge_answer in", values, "judge_answer");
            return (Criteria) this;
        }

        public Criteria andJudge_answerNotIn(List<String> values) {
            addCriterion("judge_answer not in", values, "judge_answer");
            return (Criteria) this;
        }

        public Criteria andJudge_answerBetween(String value1, String value2) {
            addCriterion("judge_answer between", value1, value2, "judge_answer");
            return (Criteria) this;
        }

        public Criteria andJudge_answerNotBetween(String value1, String value2) {
            addCriterion("judge_answer not between", value1, value2, "judge_answer");
            return (Criteria) this;
        }

        public Criteria andJudge_scoreIsNull() {
            addCriterion("judge_score is null");
            return (Criteria) this;
        }

        public Criteria andJudge_scoreIsNotNull() {
            addCriterion("judge_score is not null");
            return (Criteria) this;
        }

        public Criteria andJudge_scoreEqualTo(BigDecimal value) {
            addCriterion("judge_score =", value, "judge_score");
            return (Criteria) this;
        }

        public Criteria andJudge_scoreNotEqualTo(BigDecimal value) {
            addCriterion("judge_score <>", value, "judge_score");
            return (Criteria) this;
        }

        public Criteria andJudge_scoreGreaterThan(BigDecimal value) {
            addCriterion("judge_score >", value, "judge_score");
            return (Criteria) this;
        }

        public Criteria andJudge_scoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("judge_score >=", value, "judge_score");
            return (Criteria) this;
        }

        public Criteria andJudge_scoreLessThan(BigDecimal value) {
            addCriterion("judge_score <", value, "judge_score");
            return (Criteria) this;
        }

        public Criteria andJudge_scoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("judge_score <=", value, "judge_score");
            return (Criteria) this;
        }

        public Criteria andJudge_scoreIn(List<BigDecimal> values) {
            addCriterion("judge_score in", values, "judge_score");
            return (Criteria) this;
        }

        public Criteria andJudge_scoreNotIn(List<BigDecimal> values) {
            addCriterion("judge_score not in", values, "judge_score");
            return (Criteria) this;
        }

        public Criteria andJudge_scoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("judge_score between", value1, value2, "judge_score");
            return (Criteria) this;
        }

        public Criteria andJudge_scoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("judge_score not between", value1, value2, "judge_score");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerIsNull() {
            addCriterion("question_answer is null");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerIsNotNull() {
            addCriterion("question_answer is not null");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerEqualTo(String value) {
            addCriterion("question_answer =", value, "question_answer");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerNotEqualTo(String value) {
            addCriterion("question_answer <>", value, "question_answer");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerGreaterThan(String value) {
            addCriterion("question_answer >", value, "question_answer");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerGreaterThanOrEqualTo(String value) {
            addCriterion("question_answer >=", value, "question_answer");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerLessThan(String value) {
            addCriterion("question_answer <", value, "question_answer");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerLessThanOrEqualTo(String value) {
            addCriterion("question_answer <=", value, "question_answer");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerLike(String value) {
            addCriterion("question_answer like", value, "question_answer");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerNotLike(String value) {
            addCriterion("question_answer not like", value, "question_answer");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerIn(List<String> values) {
            addCriterion("question_answer in", values, "question_answer");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerNotIn(List<String> values) {
            addCriterion("question_answer not in", values, "question_answer");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerBetween(String value1, String value2) {
            addCriterion("question_answer between", value1, value2, "question_answer");
            return (Criteria) this;
        }

        public Criteria andQuestion_answerNotBetween(String value1, String value2) {
            addCriterion("question_answer not between", value1, value2, "question_answer");
            return (Criteria) this;
        }

        public Criteria andQuestion_sourceIsNull() {
            addCriterion("question_source is null");
            return (Criteria) this;
        }

        public Criteria andQuestion_sourceIsNotNull() {
            addCriterion("question_source is not null");
            return (Criteria) this;
        }

        public Criteria andQuestion_sourceEqualTo(BigDecimal value) {
            addCriterion("question_source =", value, "question_source");
            return (Criteria) this;
        }

        public Criteria andQuestion_sourceNotEqualTo(BigDecimal value) {
            addCriterion("question_source <>", value, "question_source");
            return (Criteria) this;
        }

        public Criteria andQuestion_sourceGreaterThan(BigDecimal value) {
            addCriterion("question_source >", value, "question_source");
            return (Criteria) this;
        }

        public Criteria andQuestion_sourceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("question_source >=", value, "question_source");
            return (Criteria) this;
        }

        public Criteria andQuestion_sourceLessThan(BigDecimal value) {
            addCriterion("question_source <", value, "question_source");
            return (Criteria) this;
        }

        public Criteria andQuestion_sourceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("question_source <=", value, "question_source");
            return (Criteria) this;
        }

        public Criteria andQuestion_sourceIn(List<BigDecimal> values) {
            addCriterion("question_source in", values, "question_source");
            return (Criteria) this;
        }

        public Criteria andQuestion_sourceNotIn(List<BigDecimal> values) {
            addCriterion("question_source not in", values, "question_source");
            return (Criteria) this;
        }

        public Criteria andQuestion_sourceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("question_source between", value1, value2, "question_source");
            return (Criteria) this;
        }

        public Criteria andQuestion_sourceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("question_source not between", value1, value2, "question_source");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerIsNull() {
            addCriterion("blanks_test_answer is null");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerIsNotNull() {
            addCriterion("blanks_test_answer is not null");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerEqualTo(String value) {
            addCriterion("blanks_test_answer =", value, "blanks_test_answer");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerNotEqualTo(String value) {
            addCriterion("blanks_test_answer <>", value, "blanks_test_answer");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerGreaterThan(String value) {
            addCriterion("blanks_test_answer >", value, "blanks_test_answer");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerGreaterThanOrEqualTo(String value) {
            addCriterion("blanks_test_answer >=", value, "blanks_test_answer");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerLessThan(String value) {
            addCriterion("blanks_test_answer <", value, "blanks_test_answer");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerLessThanOrEqualTo(String value) {
            addCriterion("blanks_test_answer <=", value, "blanks_test_answer");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerLike(String value) {
            addCriterion("blanks_test_answer like", value, "blanks_test_answer");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerNotLike(String value) {
            addCriterion("blanks_test_answer not like", value, "blanks_test_answer");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerIn(List<String> values) {
            addCriterion("blanks_test_answer in", values, "blanks_test_answer");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerNotIn(List<String> values) {
            addCriterion("blanks_test_answer not in", values, "blanks_test_answer");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerBetween(String value1, String value2) {
            addCriterion("blanks_test_answer between", value1, value2, "blanks_test_answer");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_answerNotBetween(String value1, String value2) {
            addCriterion("blanks_test_answer not between", value1, value2, "blanks_test_answer");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_sourceIsNull() {
            addCriterion("blanks_test_source is null");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_sourceIsNotNull() {
            addCriterion("blanks_test_source is not null");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_sourceEqualTo(BigDecimal value) {
            addCriterion("blanks_test_source =", value, "blanks_test_source");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_sourceNotEqualTo(BigDecimal value) {
            addCriterion("blanks_test_source <>", value, "blanks_test_source");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_sourceGreaterThan(BigDecimal value) {
            addCriterion("blanks_test_source >", value, "blanks_test_source");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_sourceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("blanks_test_source >=", value, "blanks_test_source");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_sourceLessThan(BigDecimal value) {
            addCriterion("blanks_test_source <", value, "blanks_test_source");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_sourceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("blanks_test_source <=", value, "blanks_test_source");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_sourceIn(List<BigDecimal> values) {
            addCriterion("blanks_test_source in", values, "blanks_test_source");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_sourceNotIn(List<BigDecimal> values) {
            addCriterion("blanks_test_source not in", values, "blanks_test_source");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_sourceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("blanks_test_source between", value1, value2, "blanks_test_source");
            return (Criteria) this;
        }

        public Criteria andBlanks_test_sourceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("blanks_test_source not between", value1, value2, "blanks_test_source");
            return (Criteria) this;
        }

        public Criteria andFinishedIsNull() {
            addCriterion("finished is null");
            return (Criteria) this;
        }

        public Criteria andFinishedIsNotNull() {
            addCriterion("finished is not null");
            return (Criteria) this;
        }

        public Criteria andFinishedEqualTo(String value) {
            addCriterion("finished =", value, "finished");
            return (Criteria) this;
        }

        public Criteria andFinishedNotEqualTo(String value) {
            addCriterion("finished <>", value, "finished");
            return (Criteria) this;
        }

        public Criteria andFinishedGreaterThan(String value) {
            addCriterion("finished >", value, "finished");
            return (Criteria) this;
        }

        public Criteria andFinishedGreaterThanOrEqualTo(String value) {
            addCriterion("finished >=", value, "finished");
            return (Criteria) this;
        }

        public Criteria andFinishedLessThan(String value) {
            addCriterion("finished <", value, "finished");
            return (Criteria) this;
        }

        public Criteria andFinishedLessThanOrEqualTo(String value) {
            addCriterion("finished <=", value, "finished");
            return (Criteria) this;
        }

        public Criteria andFinishedLike(String value) {
            addCriterion("finished like", value, "finished");
            return (Criteria) this;
        }

        public Criteria andFinishedNotLike(String value) {
            addCriterion("finished not like", value, "finished");
            return (Criteria) this;
        }

        public Criteria andFinishedIn(List<String> values) {
            addCriterion("finished in", values, "finished");
            return (Criteria) this;
        }

        public Criteria andFinishedNotIn(List<String> values) {
            addCriterion("finished not in", values, "finished");
            return (Criteria) this;
        }

        public Criteria andFinishedBetween(String value1, String value2) {
            addCriterion("finished between", value1, value2, "finished");
            return (Criteria) this;
        }

        public Criteria andFinishedNotBetween(String value1, String value2) {
            addCriterion("finished not between", value1, value2, "finished");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_score_t
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 17 12:41:50 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_score_t
     *
     * @mbg.generated Tue Mar 17 12:41:50 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}