package com.kuangshan.riskcontrol.model;

public class TestJudgeT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_judge_t.judge_id
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    private Integer judge_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_judge_t.edu_category_id
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    private Integer edu_category_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_judge_t.edu_knowledge_point_id
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    private Integer edu_knowledge_point_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_judge_t.judge_content
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    private String judge_content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_judge_t.answer
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    private String answer;


    private Integer deleted;


    private String explanation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_judge_t.judge_id
     *
     * @return the value of test_judge_t.judge_id
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    public Integer getJudge_id() {
        return judge_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_judge_t.judge_id
     *
     * @param judge_id the value for test_judge_t.judge_id
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    public void setJudge_id(Integer judge_id) {
        this.judge_id = judge_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_judge_t.edu_category_id
     *
     * @return the value of test_judge_t.edu_category_id
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    public Integer getEdu_category_id() {
        return edu_category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_judge_t.edu_category_id
     *
     * @param edu_category_id the value for test_judge_t.edu_category_id
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    public void setEdu_category_id(Integer edu_category_id) {
        this.edu_category_id = edu_category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_judge_t.edu_knowledge_point_id
     *
     * @return the value of test_judge_t.edu_knowledge_point_id
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    public Integer getEdu_knowledge_point_id() {
        return edu_knowledge_point_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_judge_t.edu_knowledge_point_id
     *
     * @param edu_knowledge_point_id the value for test_judge_t.edu_knowledge_point_id
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    public void setEdu_knowledge_point_id(Integer edu_knowledge_point_id) {
        this.edu_knowledge_point_id = edu_knowledge_point_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_judge_t.judge_content
     *
     * @return the value of test_judge_t.judge_content
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    public String getJudge_content() {
        return judge_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_judge_t.judge_content
     *
     * @param judge_content the value for test_judge_t.judge_content
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    public void setJudge_content(String judge_content) {
        this.judge_content = judge_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_judge_t.answer
     *
     * @return the value of test_judge_t.answer
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_judge_t.answer
     *
     * @param answer the value for test_judge_t.answer
     *
     * @mbg.generated Sat Feb 01 14:35:23 CST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }


    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    public String getExplanation() {
        return explanation;
    }

    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }


    @Override
    public String toString() {
        return "TestJudgeT{" +
                "judge_id=" + judge_id +
                ", edu_category_id=" + edu_category_id +
                ", edu_knowledge_point_id=" + edu_knowledge_point_id +
                ", judge_content='" + judge_content + '\'' +
                ", answer='" + answer + '\'' +
                ", deleted=" + deleted +
                ", explanation='" + explanation + '\'' +
                '}';
    }


}