package com.kuangshan.riskcontrol.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TestInfoTExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public TestInfoTExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTest_idIsNull() {
            addCriterion("test_id is null");
            return (Criteria) this;
        }

        public Criteria andTest_idIsNotNull() {
            addCriterion("test_id is not null");
            return (Criteria) this;
        }

        public Criteria andTest_idEqualTo(Integer value) {
            addCriterion("test_id =", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idNotEqualTo(Integer value) {
            addCriterion("test_id <>", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idGreaterThan(Integer value) {
            addCriterion("test_id >", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_id >=", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idLessThan(Integer value) {
            addCriterion("test_id <", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idLessThanOrEqualTo(Integer value) {
            addCriterion("test_id <=", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idIn(List<Integer> values) {
            addCriterion("test_id in", values, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idNotIn(List<Integer> values) {
            addCriterion("test_id not in", values, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idBetween(Integer value1, Integer value2) {
            addCriterion("test_id between", value1, value2, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idNotBetween(Integer value1, Integer value2) {
            addCriterion("test_id not between", value1, value2, "test_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idIsNull() {
            addCriterion("education_id is null");
            return (Criteria) this;
        }

        public Criteria andEducation_idIsNotNull() {
            addCriterion("education_id is not null");
            return (Criteria) this;
        }

        public Criteria andEducation_idEqualTo(Integer value) {
            addCriterion("education_id =", value, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idNotEqualTo(Integer value) {
            addCriterion("education_id <>", value, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idGreaterThan(Integer value) {
            addCriterion("education_id >", value, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("education_id >=", value, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idLessThan(Integer value) {
            addCriterion("education_id <", value, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idLessThanOrEqualTo(Integer value) {
            addCriterion("education_id <=", value, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idIn(List<Integer> values) {
            addCriterion("education_id in", values, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idNotIn(List<Integer> values) {
            addCriterion("education_id not in", values, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idBetween(Integer value1, Integer value2) {
            addCriterion("education_id between", value1, value2, "education_id");
            return (Criteria) this;
        }

        public Criteria andEducation_idNotBetween(Integer value1, Integer value2) {
            addCriterion("education_id not between", value1, value2, "education_id");
            return (Criteria) this;
        }

        public Criteria andTest_nameIsNull() {
            addCriterion("test_name is null");
            return (Criteria) this;
        }

        public Criteria andTest_nameIsNotNull() {
            addCriterion("test_name is not null");
            return (Criteria) this;
        }

        public Criteria andTest_nameEqualTo(String value) {
            addCriterion("test_name =", value, "test_name");
            return (Criteria) this;
        }

        public Criteria andTest_nameNotEqualTo(String value) {
            addCriterion("test_name <>", value, "test_name");
            return (Criteria) this;
        }

        public Criteria andTest_nameGreaterThan(String value) {
            addCriterion("test_name >", value, "test_name");
            return (Criteria) this;
        }

        public Criteria andTest_nameGreaterThanOrEqualTo(String value) {
            addCriterion("test_name >=", value, "test_name");
            return (Criteria) this;
        }

        public Criteria andTest_nameLessThan(String value) {
            addCriterion("test_name <", value, "test_name");
            return (Criteria) this;
        }

        public Criteria andTest_nameLessThanOrEqualTo(String value) {
            addCriterion("test_name <=", value, "test_name");
            return (Criteria) this;
        }

        public Criteria andTest_nameLike(String value) {
            addCriterion("test_name like", value, "test_name");
            return (Criteria) this;
        }

        public Criteria andTest_nameNotLike(String value) {
            addCriterion("test_name not like", value, "test_name");
            return (Criteria) this;
        }

        public Criteria andTest_nameIn(List<String> values) {
            addCriterion("test_name in", values, "test_name");
            return (Criteria) this;
        }

        public Criteria andTest_nameNotIn(List<String> values) {
            addCriterion("test_name not in", values, "test_name");
            return (Criteria) this;
        }

        public Criteria andTest_nameBetween(String value1, String value2) {
            addCriterion("test_name between", value1, value2, "test_name");
            return (Criteria) this;
        }

        public Criteria andTest_nameNotBetween(String value1, String value2) {
            addCriterion("test_name not between", value1, value2, "test_name");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idIsNull() {
            addCriterion("edu_category_id is null");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idIsNotNull() {
            addCriterion("edu_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idEqualTo(Integer value) {
            addCriterion("edu_category_id =", value, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idNotEqualTo(Integer value) {
            addCriterion("edu_category_id <>", value, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idGreaterThan(Integer value) {
            addCriterion("edu_category_id >", value, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("edu_category_id >=", value, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idLessThan(Integer value) {
            addCriterion("edu_category_id <", value, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idLessThanOrEqualTo(Integer value) {
            addCriterion("edu_category_id <=", value, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idIn(List<Integer> values) {
            addCriterion("edu_category_id in", values, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idNotIn(List<Integer> values) {
            addCriterion("edu_category_id not in", values, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idBetween(Integer value1, Integer value2) {
            addCriterion("edu_category_id between", value1, value2, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andEdu_category_idNotBetween(Integer value1, Integer value2) {
            addCriterion("edu_category_id not between", value1, value2, "edu_category_id");
            return (Criteria) this;
        }

        public Criteria andTest_addressIsNull() {
            addCriterion("test_address is null");
            return (Criteria) this;
        }

        public Criteria andTest_addressIsNotNull() {
            addCriterion("test_address is not null");
            return (Criteria) this;
        }

        public Criteria andTest_addressEqualTo(String value) {
            addCriterion("test_address =", value, "test_address");
            return (Criteria) this;
        }

        public Criteria andTest_addressNotEqualTo(String value) {
            addCriterion("test_address <>", value, "test_address");
            return (Criteria) this;
        }

        public Criteria andTest_addressGreaterThan(String value) {
            addCriterion("test_address >", value, "test_address");
            return (Criteria) this;
        }

        public Criteria andTest_addressGreaterThanOrEqualTo(String value) {
            addCriterion("test_address >=", value, "test_address");
            return (Criteria) this;
        }

        public Criteria andTest_addressLessThan(String value) {
            addCriterion("test_address <", value, "test_address");
            return (Criteria) this;
        }

        public Criteria andTest_addressLessThanOrEqualTo(String value) {
            addCriterion("test_address <=", value, "test_address");
            return (Criteria) this;
        }

        public Criteria andTest_addressLike(String value) {
            addCriterion("test_address like", value, "test_address");
            return (Criteria) this;
        }

        public Criteria andTest_addressNotLike(String value) {
            addCriterion("test_address not like", value, "test_address");
            return (Criteria) this;
        }

        public Criteria andTest_addressIn(List<String> values) {
            addCriterion("test_address in", values, "test_address");
            return (Criteria) this;
        }

        public Criteria andTest_addressNotIn(List<String> values) {
            addCriterion("test_address not in", values, "test_address");
            return (Criteria) this;
        }

        public Criteria andTest_addressBetween(String value1, String value2) {
            addCriterion("test_address between", value1, value2, "test_address");
            return (Criteria) this;
        }

        public Criteria andTest_addressNotBetween(String value1, String value2) {
            addCriterion("test_address not between", value1, value2, "test_address");
            return (Criteria) this;
        }

        public Criteria andTest_start_timeIsNull() {
            addCriterion("test_start_time is null");
            return (Criteria) this;
        }

        public Criteria andTest_start_timeIsNotNull() {
            addCriterion("test_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andTest_start_timeEqualTo(Date value) {
            addCriterion("test_start_time =", value, "test_start_time");
            return (Criteria) this;
        }

        public Criteria andTest_start_timeNotEqualTo(Date value) {
            addCriterion("test_start_time <>", value, "test_start_time");
            return (Criteria) this;
        }

        public Criteria andTest_start_timeGreaterThan(Date value) {
            addCriterion("test_start_time >", value, "test_start_time");
            return (Criteria) this;
        }

        public Criteria andTest_start_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("test_start_time >=", value, "test_start_time");
            return (Criteria) this;
        }

        public Criteria andTest_start_timeLessThan(Date value) {
            addCriterion("test_start_time <", value, "test_start_time");
            return (Criteria) this;
        }

        public Criteria andTest_start_timeLessThanOrEqualTo(Date value) {
            addCriterion("test_start_time <=", value, "test_start_time");
            return (Criteria) this;
        }

        public Criteria andTest_start_timeIn(List<Date> values) {
            addCriterion("test_start_time in", values, "test_start_time");
            return (Criteria) this;
        }

        public Criteria andTest_start_timeNotIn(List<Date> values) {
            addCriterion("test_start_time not in", values, "test_start_time");
            return (Criteria) this;
        }

        public Criteria andTest_start_timeBetween(Date value1, Date value2) {
            addCriterion("test_start_time between", value1, value2, "test_start_time");
            return (Criteria) this;
        }

        public Criteria andTest_start_timeNotBetween(Date value1, Date value2) {
            addCriterion("test_start_time not between", value1, value2, "test_start_time");
            return (Criteria) this;
        }

        public Criteria andTest_end_timeIsNull() {
            addCriterion("test_end_time is null");
            return (Criteria) this;
        }

        public Criteria andTest_end_timeIsNotNull() {
            addCriterion("test_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andTest_end_timeEqualTo(Date value) {
            addCriterion("test_end_time =", value, "test_end_time");
            return (Criteria) this;
        }

        public Criteria andTest_end_timeNotEqualTo(Date value) {
            addCriterion("test_end_time <>", value, "test_end_time");
            return (Criteria) this;
        }

        public Criteria andTest_end_timeGreaterThan(Date value) {
            addCriterion("test_end_time >", value, "test_end_time");
            return (Criteria) this;
        }

        public Criteria andTest_end_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("test_end_time >=", value, "test_end_time");
            return (Criteria) this;
        }

        public Criteria andTest_end_timeLessThan(Date value) {
            addCriterion("test_end_time <", value, "test_end_time");
            return (Criteria) this;
        }

        public Criteria andTest_end_timeLessThanOrEqualTo(Date value) {
            addCriterion("test_end_time <=", value, "test_end_time");
            return (Criteria) this;
        }

        public Criteria andTest_end_timeIn(List<Date> values) {
            addCriterion("test_end_time in", values, "test_end_time");
            return (Criteria) this;
        }

        public Criteria andTest_end_timeNotIn(List<Date> values) {
            addCriterion("test_end_time not in", values, "test_end_time");
            return (Criteria) this;
        }

        public Criteria andTest_end_timeBetween(Date value1, Date value2) {
            addCriterion("test_end_time between", value1, value2, "test_end_time");
            return (Criteria) this;
        }

        public Criteria andTest_end_timeNotBetween(Date value1, Date value2) {
            addCriterion("test_end_time not between", value1, value2, "test_end_time");
            return (Criteria) this;
        }

        public Criteria andRelated_test_idIsNull() {
            addCriterion("related_test_id is null");
            return (Criteria) this;
        }

        public Criteria andRelated_test_idIsNotNull() {
            addCriterion("related_test_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelated_test_idEqualTo(Integer value) {
            addCriterion("related_test_id =", value, "related_test_id");
            return (Criteria) this;
        }

        public Criteria andRelated_test_idNotEqualTo(Integer value) {
            addCriterion("related_test_id <>", value, "related_test_id");
            return (Criteria) this;
        }

        public Criteria andRelated_test_idGreaterThan(Integer value) {
            addCriterion("related_test_id >", value, "related_test_id");
            return (Criteria) this;
        }

        public Criteria andRelated_test_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("related_test_id >=", value, "related_test_id");
            return (Criteria) this;
        }

        public Criteria andRelated_test_idLessThan(Integer value) {
            addCriterion("related_test_id <", value, "related_test_id");
            return (Criteria) this;
        }

        public Criteria andRelated_test_idLessThanOrEqualTo(Integer value) {
            addCriterion("related_test_id <=", value, "related_test_id");
            return (Criteria) this;
        }

        public Criteria andRelated_test_idIn(List<Integer> values) {
            addCriterion("related_test_id in", values, "related_test_id");
            return (Criteria) this;
        }

        public Criteria andRelated_test_idNotIn(List<Integer> values) {
            addCriterion("related_test_id not in", values, "related_test_id");
            return (Criteria) this;
        }

        public Criteria andRelated_test_idBetween(Integer value1, Integer value2) {
            addCriterion("related_test_id between", value1, value2, "related_test_id");
            return (Criteria) this;
        }

        public Criteria andRelated_test_idNotBetween(Integer value1, Integer value2) {
            addCriterion("related_test_id not between", value1, value2, "related_test_id");
            return (Criteria) this;
        }

        public Criteria andTest_typeIsNull() {
            addCriterion("test_type is null");
            return (Criteria) this;
        }

        public Criteria andTest_typeIsNotNull() {
            addCriterion("test_type is not null");
            return (Criteria) this;
        }

        public Criteria andTest_typeEqualTo(String value) {
            addCriterion("test_type =", value, "test_type");
            return (Criteria) this;
        }

        public Criteria andTest_typeNotEqualTo(String value) {
            addCriterion("test_type <>", value, "test_type");
            return (Criteria) this;
        }

        public Criteria andTest_typeGreaterThan(String value) {
            addCriterion("test_type >", value, "test_type");
            return (Criteria) this;
        }

        public Criteria andTest_typeGreaterThanOrEqualTo(String value) {
            addCriterion("test_type >=", value, "test_type");
            return (Criteria) this;
        }

        public Criteria andTest_typeLessThan(String value) {
            addCriterion("test_type <", value, "test_type");
            return (Criteria) this;
        }

        public Criteria andTest_typeLessThanOrEqualTo(String value) {
            addCriterion("test_type <=", value, "test_type");
            return (Criteria) this;
        }

        public Criteria andTest_typeLike(String value) {
            addCriterion("test_type like", value, "test_type");
            return (Criteria) this;
        }

        public Criteria andTest_typeNotLike(String value) {
            addCriterion("test_type not like", value, "test_type");
            return (Criteria) this;
        }

        public Criteria andTest_typeIn(List<String> values) {
            addCriterion("test_type in", values, "test_type");
            return (Criteria) this;
        }

        public Criteria andTest_typeNotIn(List<String> values) {
            addCriterion("test_type not in", values, "test_type");
            return (Criteria) this;
        }

        public Criteria andTest_typeBetween(String value1, String value2) {
            addCriterion("test_type between", value1, value2, "test_type");
            return (Criteria) this;
        }

        public Criteria andTest_typeNotBetween(String value1, String value2) {
            addCriterion("test_type not between", value1, value2, "test_type");
            return (Criteria) this;
        }

        public Criteria andScore_modeIsNull() {
            addCriterion("score_mode is null");
            return (Criteria) this;
        }

        public Criteria andScore_modeIsNotNull() {
            addCriterion("score_mode is not null");
            return (Criteria) this;
        }

        public Criteria andScore_modeEqualTo(String value) {
            addCriterion("score_mode =", value, "score_mode");
            return (Criteria) this;
        }

        public Criteria andScore_modeNotEqualTo(String value) {
            addCriterion("score_mode <>", value, "score_mode");
            return (Criteria) this;
        }

        public Criteria andScore_modeGreaterThan(String value) {
            addCriterion("score_mode >", value, "score_mode");
            return (Criteria) this;
        }

        public Criteria andScore_modeGreaterThanOrEqualTo(String value) {
            addCriterion("score_mode >=", value, "score_mode");
            return (Criteria) this;
        }

        public Criteria andScore_modeLessThan(String value) {
            addCriterion("score_mode <", value, "score_mode");
            return (Criteria) this;
        }

        public Criteria andScore_modeLessThanOrEqualTo(String value) {
            addCriterion("score_mode <=", value, "score_mode");
            return (Criteria) this;
        }

        public Criteria andScore_modeLike(String value) {
            addCriterion("score_mode like", value, "score_mode");
            return (Criteria) this;
        }

        public Criteria andScore_modeNotLike(String value) {
            addCriterion("score_mode not like", value, "score_mode");
            return (Criteria) this;
        }

        public Criteria andScore_modeIn(List<String> values) {
            addCriterion("score_mode in", values, "score_mode");
            return (Criteria) this;
        }

        public Criteria andScore_modeNotIn(List<String> values) {
            addCriterion("score_mode not in", values, "score_mode");
            return (Criteria) this;
        }

        public Criteria andScore_modeBetween(String value1, String value2) {
            addCriterion("score_mode between", value1, value2, "score_mode");
            return (Criteria) this;
        }

        public Criteria andScore_modeNotBetween(String value1, String value2) {
            addCriterion("score_mode not between", value1, value2, "score_mode");
            return (Criteria) this;
        }

        public Criteria andIs_onlineIsNull() {
            addCriterion("is_online is null");
            return (Criteria) this;
        }

        public Criteria andIs_onlineIsNotNull() {
            addCriterion("is_online is not null");
            return (Criteria) this;
        }

        public Criteria andIs_onlineEqualTo(String value) {
            addCriterion("is_online =", value, "is_online");
            return (Criteria) this;
        }

        public Criteria andIs_onlineNotEqualTo(String value) {
            addCriterion("is_online <>", value, "is_online");
            return (Criteria) this;
        }

        public Criteria andIs_onlineGreaterThan(String value) {
            addCriterion("is_online >", value, "is_online");
            return (Criteria) this;
        }

        public Criteria andIs_onlineGreaterThanOrEqualTo(String value) {
            addCriterion("is_online >=", value, "is_online");
            return (Criteria) this;
        }

        public Criteria andIs_onlineLessThan(String value) {
            addCriterion("is_online <", value, "is_online");
            return (Criteria) this;
        }

        public Criteria andIs_onlineLessThanOrEqualTo(String value) {
            addCriterion("is_online <=", value, "is_online");
            return (Criteria) this;
        }

        public Criteria andIs_onlineLike(String value) {
            addCriterion("is_online like", value, "is_online");
            return (Criteria) this;
        }

        public Criteria andIs_onlineNotLike(String value) {
            addCriterion("is_online not like", value, "is_online");
            return (Criteria) this;
        }

        public Criteria andIs_onlineIn(List<String> values) {
            addCriterion("is_online in", values, "is_online");
            return (Criteria) this;
        }

        public Criteria andIs_onlineNotIn(List<String> values) {
            addCriterion("is_online not in", values, "is_online");
            return (Criteria) this;
        }

        public Criteria andIs_onlineBetween(String value1, String value2) {
            addCriterion("is_online between", value1, value2, "is_online");
            return (Criteria) this;
        }

        public Criteria andIs_onlineNotBetween(String value1, String value2) {
            addCriterion("is_online not between", value1, value2, "is_online");
            return (Criteria) this;
        }

        public Criteria andIs_releasedIsNull() {
            addCriterion("is_released is null");
            return (Criteria) this;
        }

        public Criteria andIs_releasedIsNotNull() {
            addCriterion("is_released is not null");
            return (Criteria) this;
        }

        public Criteria andIs_releasedEqualTo(String value) {
            addCriterion("is_released =", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedNotEqualTo(String value) {
            addCriterion("is_released <>", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedGreaterThan(String value) {
            addCriterion("is_released >", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedGreaterThanOrEqualTo(String value) {
            addCriterion("is_released >=", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedLessThan(String value) {
            addCriterion("is_released <", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedLessThanOrEqualTo(String value) {
            addCriterion("is_released <=", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedLike(String value) {
            addCriterion("is_released like", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedNotLike(String value) {
            addCriterion("is_released not like", value, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedIn(List<String> values) {
            addCriterion("is_released in", values, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedNotIn(List<String> values) {
            addCriterion("is_released not in", values, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedBetween(String value1, String value2) {
            addCriterion("is_released between", value1, value2, "is_released");
            return (Criteria) this;
        }

        public Criteria andIs_releasedNotBetween(String value1, String value2) {
            addCriterion("is_released not between", value1, value2, "is_released");
            return (Criteria) this;
        }

        public Criteria andTest_timeIsNull() {
            addCriterion("test_time is null");
            return (Criteria) this;
        }

        public Criteria andTest_timeIsNotNull() {
            addCriterion("test_time is not null");
            return (Criteria) this;
        }

        public Criteria andTest_timeEqualTo(Integer value) {
            addCriterion("test_time =", value, "test_time");
            return (Criteria) this;
        }

        public Criteria andTest_timeNotEqualTo(Integer value) {
            addCriterion("test_time <>", value, "test_time");
            return (Criteria) this;
        }

        public Criteria andTest_timeGreaterThan(Integer value) {
            addCriterion("test_time >", value, "test_time");
            return (Criteria) this;
        }

        public Criteria andTest_timeGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_time >=", value, "test_time");
            return (Criteria) this;
        }

        public Criteria andTest_timeLessThan(Integer value) {
            addCriterion("test_time <", value, "test_time");
            return (Criteria) this;
        }

        public Criteria andTest_timeLessThanOrEqualTo(Integer value) {
            addCriterion("test_time <=", value, "test_time");
            return (Criteria) this;
        }

        public Criteria andTest_timeIn(List<Integer> values) {
            addCriterion("test_time in", values, "test_time");
            return (Criteria) this;
        }

        public Criteria andTest_timeNotIn(List<Integer> values) {
            addCriterion("test_time not in", values, "test_time");
            return (Criteria) this;
        }

        public Criteria andTest_timeBetween(Integer value1, Integer value2) {
            addCriterion("test_time between", value1, value2, "test_time");
            return (Criteria) this;
        }

        public Criteria andTest_timeNotBetween(Integer value1, Integer value2) {
            addCriterion("test_time not between", value1, value2, "test_time");
            return (Criteria) this;
        }

        public Criteria andIs_submittedIsNull() {
            addCriterion("is_submitted is null");
            return (Criteria) this;
        }

        public Criteria andIs_submittedIsNotNull() {
            addCriterion("is_submitted is not null");
            return (Criteria) this;
        }

        public Criteria andIs_submittedEqualTo(Integer value) {
            addCriterion("is_submitted =", value, "is_submitted");
            return (Criteria) this;
        }

        public Criteria andIs_submittedNotEqualTo(Integer value) {
            addCriterion("is_submitted <>", value, "is_submitted");
            return (Criteria) this;
        }

        public Criteria andIs_submittedGreaterThan(Integer value) {
            addCriterion("is_submitted >", value, "is_submitted");
            return (Criteria) this;
        }

        public Criteria andIs_submittedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_submitted >=", value, "is_submitted");
            return (Criteria) this;
        }

        public Criteria andIs_submittedLessThan(Integer value) {
            addCriterion("is_submitted <", value, "is_submitted");
            return (Criteria) this;
        }

        public Criteria andIs_submittedLessThanOrEqualTo(Integer value) {
            addCriterion("is_submitted <=", value, "is_submitted");
            return (Criteria) this;
        }

        public Criteria andIs_submittedIn(List<Integer> values) {
            addCriterion("is_submitted in", values, "is_submitted");
            return (Criteria) this;
        }

        public Criteria andIs_submittedNotIn(List<Integer> values) {
            addCriterion("is_submitted not in", values, "is_submitted");
            return (Criteria) this;
        }

        public Criteria andIs_submittedBetween(Integer value1, Integer value2) {
            addCriterion("is_submitted between", value1, value2, "is_submitted");
            return (Criteria) this;
        }

        public Criteria andIs_submittedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_submitted not between", value1, value2, "is_submitted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_info_t
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 29 11:50:20 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_info_t
     *
     * @mbg.generated Sat Feb 29 11:50:20 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}