package com.kuangshan.riskcontrol.dao;

import com.kuangshan.riskcontrol.model.DatadictionaryT;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DatadictionaryTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datadictionary_t
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    int deleteByPrimaryKey(Integer dditemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datadictionary_t
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    int insert(DatadictionaryT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datadictionary_t
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    int insertSelective(DatadictionaryT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datadictionary_t
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    DatadictionaryT selectByPrimaryKey(Integer dditemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datadictionary_t
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    int updateByPrimaryKeySelective(DatadictionaryT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datadictionary_t
     *
     * @mbg.generated Sun Mar 03 18:06:34 CST 2019
     */
    int updateByPrimaryKey(DatadictionaryT record);

    List<DatadictionaryT> getAccidentName(@Param("number")String number);

    List<DatadictionaryT> getDDItemValueByCategoryNum(@Param("DDCategoryNum")String DDCategoryNum);
}