package com.kuangshan.riskcontrol.dao;

import com.kuangshan.riskcontrol.model.EducationCategoryT;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EducationCategoryTMapper {

    /**
     * 根据页码和查询条件获取数据
     * @param conditions 条件
     * @param start 页面
     * @param limit 多少条
     * @return 数据列表
     */
    List<EducationCategoryT> selectAllByPage(
            @Param("conditions") String conditions,
            @Param("start") int start,
            @Param("limit") int limit);


    /**
     * 根据条件获取页面数据总数
     * @param conditions 条件
     * @return 总数
     */
    int selectAllNum(@Param("conditions") String conditions);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_category_t
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    int deleteByPrimaryKey(Integer edu_category_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_category_t
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    int insert(EducationCategoryT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_category_t
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    int insertSelective(EducationCategoryT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_category_t
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    EducationCategoryT selectByPrimaryKey(Integer edu_category_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_category_t
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    int updateByPrimaryKeySelective(EducationCategoryT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_category_t
     *
     * @mbg.generated Mon Jan 13 17:22:49 CST 2020
     */
    int updateByPrimaryKey(EducationCategoryT record);


    List<EducationCategoryT> selectAll();
}