package com.kuangshan.riskcontrol.dao;

import com.kuangshan.riskcontrol.model.EducationResourceT;
import com.kuangshan.riskcontrol.model.EducationResourceTExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface EducationResourceTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_resource_t
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    long countByExample(EducationResourceTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_resource_t
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    int deleteByExample(EducationResourceTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_resource_t
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    int deleteByPrimaryKey(Integer edu_resource_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_resource_t
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    int insert(EducationResourceT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_resource_t
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    int insertSelective(EducationResourceT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_resource_t
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    List<EducationResourceT> selectByExample(EducationResourceTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_resource_t
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    EducationResourceT selectByPrimaryKey(Integer edu_resource_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_resource_t
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") EducationResourceT record, @Param("example") EducationResourceTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_resource_t
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    int updateByExample(@Param("record") EducationResourceT record, @Param("example") EducationResourceTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_resource_t
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    int updateByPrimaryKeySelective(EducationResourceT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_resource_t
     *
     * @mbg.generated Tue Jan 14 16:26:03 CST 2020
     */
    int updateByPrimaryKey(EducationResourceT record);

    int getLastResID();

    int getLastEduResID();

    int setIsReleased(@Param("id")Integer id);


    //获取一级目录
    List<Map<String,Object>> getResourceList( String userID);

    //获取下拉框的全部培训类型
    List<Map> getResCategory();

    //获取各一级目录下的二级文件
    List<Map> getScondItem(Integer resID);

    List<Integer> getReleasedStatus(@Param("id_list") List<String> id_list);

    List<String> getCultivate(Integer resID);
}