package com.kuangshan.riskcontrol.dao;

import com.kuangshan.riskcontrol.model.EducationInfoT;
import com.kuangshan.riskcontrol.model.EducationInfoTExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface EducationInfoTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    long countByExample(EducationInfoTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    int deleteByExample(EducationInfoTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    int deleteByPrimaryKey(Integer education_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    int insert(EducationInfoT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    int insertSelective(EducationInfoT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    List<EducationInfoT> selectByExample(EducationInfoTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    EducationInfoT selectByPrimaryKey(Integer education_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") EducationInfoT record, @Param("example") EducationInfoTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    int updateByExample(@Param("record") EducationInfoT record, @Param("example") EducationInfoTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    int updateByPrimaryKeySelective(EducationInfoT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education_info_t
     *
     * @mbg.generated Sat Feb 29 12:40:12 CST 2020
     */
    int updateByPrimaryKey(EducationInfoT record);

    int deleteMulEducation(@Param("idlist") List<String> idlist);

    int setIsReleased(@Param("education_id")Integer education_id);

    int setMulReleased(@Param("id_list")List<String> id_list);

    int getEducationNumberByID(@Param("education_id")Integer education_id);

    List<Integer> getMulReleasedStatus(@Param("id_list")List<String> id_list);

    String getReleasedStatus(@Param("id")Integer id);

    Map<String, Object> getNameAndCategoryByID(@Param("education_id")Integer education_id);

    int getFinishedStatus(@Param("education_id")Integer education_id);

    int setIsFinishedByID(@Param("education_id")Integer education_id);

    int setMulFinished(@Param("id_list")List<String> id_list);

    int setNonFinished(@Param("id")Integer id);
}