package com.kuangshan.riskcontrol.dao;

import com.kuangshan.riskcontrol.model.InstitutionT;
import com.kuangshan.riskcontrol.model.InstitutionTExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InstitutionTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    long countByExample(InstitutionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    int deleteByExample(InstitutionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    int deleteByPrimaryKey(String institutionnum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    int insert(InstitutionT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    int insertSelective(InstitutionT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    List<InstitutionT> selectByExample(InstitutionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    InstitutionT selectByPrimaryKey(String institutionnum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") InstitutionT record, @Param("example") InstitutionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    int updateByExample(@Param("record") InstitutionT record, @Param("example") InstitutionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    int updateByPrimaryKeySelective(InstitutionT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_t
     *
     * @mbg.generated Mon Sep 24 21:25:21 CST 2018
     */
    int updateByPrimaryKey(InstitutionT record);
    
    List<InstitutionT> selectAllByPage(@Param("conditions") String conditions, @Param("start") int start, @Param("limit") int limit);

    int selectAllNum(@Param("conditions") String conditions);

    List<InstitutionT> selectByPeopleInCharge(InstitutionTExample example);
    
    List<InstitutionT> selectByCategory(String category);
    
    List<InstitutionT> selectByInstitutionCategory(InstitutionTExample example);
    
    List<InstitutionT> getInstitutionExceptClass(InstitutionTExample example);
    
    InstitutionT selectByInfo(String InstitutionNum);
    
    List<InstitutionT> checkIsRoleExist(String InstitutionNum);
   
    int deleteInstitutionByNum(@Param("InstitutionNum") String InstitutionNum, @Param("deletetime") Date deletetime);


    List<InstitutionT> getInstitutionList();
    List<InstitutionT> getInstitutionByID(@Param("institutionnum")String num);

    List<InstitutionT> selectAll();
}