package com.kuangshan.riskcontrol.dao;

import com.kuangshan.riskcontrol.model.ModuleinfoT;
import java.util.List;

public interface ModuleinfoTMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleinfo_t
     *
     * @mbg.generated Thu Oct 25 17:30:38 CST 2018
     */
    int deleteByPrimaryKey(String modulenum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleinfo_t
     *
     * @mbg.generated Thu Oct 25 17:30:38 CST 2018
     */
    int insert(ModuleinfoT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleinfo_t
     *
     * @mbg.generated Thu Oct 25 17:30:38 CST 2018
     */
    int insertSelective(ModuleinfoT record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleinfo_t
     *
     * @mbg.generated Thu Oct 25 17:30:38 CST 2018
     */
    ModuleinfoT selectByPrimaryKey(String modulenum);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleinfo_t
     *
     * @mbg.generated Thu Oct 25 17:30:38 CST 2018
     */
    int updateByPrimaryKeySelective(ModuleinfoT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleinfo_t
     *
     * @mbg.generated Thu Oct 25 17:30:38 CST 2018
     */
    int updateByPrimaryKey(ModuleinfoT record);

    List<ModuleinfoT> selectAllModule();
    
    List<ModuleinfoT> selectFirstModule();
    
    List<ModuleinfoT> selectSecondModule();
}