package com.kuangshan.riskcontrol.dao;

import com.kuangshan.riskcontrol.model.OfflineTestPaperT;
import org.apache.ibatis.annotations.Param;

public interface OfflineTestPaperTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_test_paper_t
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    int deleteByPrimaryKey(Integer paper_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_test_paper_t
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    int insert(OfflineTestPaperT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_test_paper_t
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    int insertSelective(OfflineTestPaperT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_test_paper_t
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    OfflineTestPaperT selectByPrimaryKey(Integer paper_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_test_paper_t
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    int updateByPrimaryKeySelective(OfflineTestPaperT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_test_paper_t
     *
     * @mbg.generated Sun Feb 02 18:03:47 CST 2020
     */
    int updateByPrimaryKey(OfflineTestPaperT record);

    int deleteByTestID(@Param("test_id")Integer test_id);
}