package com.kuangshan.riskcontrol.dao;

import com.kuangshan.riskcontrol.model.OnlineEduTimeT;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface OnlineEduTimeTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_edu_time_t
     *
     * @mbg.generated Tue Feb 18 19:20:14 CST 2020
     */
    int deleteByPrimaryKey(Integer online_edu_time_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_edu_time_t
     *
     * @mbg.generated Tue Feb 18 19:20:14 CST 2020
     */
    int insert(OnlineEduTimeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_edu_time_t
     *
     * @mbg.generated Tue Feb 18 19:20:14 CST 2020
     */
    int insertSelective(OnlineEduTimeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_edu_time_t
     *
     * @mbg.generated Tue Feb 18 19:20:14 CST 2020
     */
    OnlineEduTimeT selectByPrimaryKey(Integer online_edu_time_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_edu_time_t
     *
     * @mbg.generated Tue Feb 18 19:20:14 CST 2020
     */
    int updateByPrimaryKeySelective(OnlineEduTimeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_edu_time_t
     *
     * @mbg.generated Tue Feb 18 19:20:14 CST 2020
     */
    int updateByPrimaryKey(OnlineEduTimeT record);

    List<Map> getCultivateInfo(Integer resID);

    int hasRecord(@Param("upload_file_name")String upload_file_name,@Param("resId")Integer resId);

    int updateTotalTIme(@Param("upload_file_name") String upload_file_name,@Param("total_time") Integer total_time);
    List<Map<String,Object>> getCultivateNowPoint(String userID);

    int getCultivateTotalPoint(String educationName);

    List<Map<String, Object>> getSelfStudyPoint(String userID);

}