package com.kuangshan.riskcontrol.dao;

import com.kuangshan.riskcontrol.model.ResourceContentT;
import com.kuangshan.riskcontrol.model.ResourceContentTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceContentTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    long countByExample(ResourceContentTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    int deleteByExample(ResourceContentTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    int deleteByPrimaryKey(Integer res_content_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    int insert(ResourceContentT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    int insertSelective(ResourceContentT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    List<ResourceContentT> selectByExample(ResourceContentTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    ResourceContentT selectByPrimaryKey(Integer res_content_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") ResourceContentT record, @Param("example") ResourceContentTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    int updateByExample(@Param("record") ResourceContentT record, @Param("example") ResourceContentTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    int updateByPrimaryKeySelective(ResourceContentT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_content_t
     *
     * @mbg.generated Sun Jan 19 20:23:56 CST 2020
     */
    int updateByPrimaryKey(ResourceContentT record);

    int deleteByResID(@Param("edu_resource_id") Integer edu_resource_id);
}