package com.kuangshan.riskcontrol.dao;

import com.kuangshan.riskcontrol.model.RollEducationT;
import com.kuangshan.riskcontrol.model.RollEducationTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RollEducationTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roll_education_t
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    long countByExample(RollEducationTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roll_education_t
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    int deleteByExample(RollEducationTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roll_education_t
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    int deleteByPrimaryKey(Integer roll_education_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roll_education_t
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    int insert(RollEducationT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roll_education_t
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    int insertSelective(RollEducationT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roll_education_t
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    List<RollEducationT> selectByExample(RollEducationTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roll_education_t
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    RollEducationT selectByPrimaryKey(Integer roll_education_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roll_education_t
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") RollEducationT record, @Param("example") RollEducationTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roll_education_t
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    int updateByExample(@Param("record") RollEducationT record, @Param("example") RollEducationTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roll_education_t
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    int updateByPrimaryKeySelective(RollEducationT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roll_education_t
     *
     * @mbg.generated Thu Mar 05 16:03:08 CST 2020
     */
    int updateByPrimaryKey(RollEducationT record);

    int setTestID(@Param("test_id")Integer test_id, @Param("education_id")Integer education_id);

    int updateMulTestID(@Param("id_list")List<String> id_list);

    int deleteEnterForm(@Param("id_list")List<String> id_list);

    List<RollEducationT> getTestIDByEID(@Param("id_list")List<String> id_list);

    int deleteMulEmployee(@Param("id_list")List<String> id_list);

    Long getCountByEID(@Param("education_id")Integer id);

    List<RollEducationT> getRollInfoByEID(@Param("test_id")Integer test_id,@Param("education_id")Integer edcation_id);


    int deleteRollInfo(@Param("test_id")Integer test_id);//在未绑定培训的情况下删除考试报名员工

    int updateRollInfo(@Param("test_id")Integer test_id);//再绑定培训的情况下清除考生密码和考试ID
}